### ISSUE TITLE
Blocks look incorrect when generated from worldgen but when placed by hand they have the correct blockstate

### ISSUE THREAD

**Issue by legosteenjaap** [AstralOrdana/Immersive-Weathering#102]
### Before
![2022-07-02_13 48 40](https://user-images.githubusercontent.com/50271899/177002161-d9b8268e-c869-4cbd-97ee-d43b97a8a0a4.png)
### After
![2022-07-02_13 49 22](https://user-images.githubusercontent.com/50271899/177002196-281317a9-145d-41fc-b2aa-930588bf94fe.png)

**Comment by AstralOrdana** [comment]
This is working as intended, the cryosol and permafrost will convert to their proper states over time via random ticks
