### ISSUE TITLE
Bars Z-Fighting

### ISSUE THREAD

**Issue by ardissaps** [AstralOrdana/Immersive-Weathering#103]
![image](https://user-images.githubusercontent.com/82106625/177007466-8d777504-dedd-4d4a-83ea-64c477e723e9.png)

**Comment by AstralOrdana** [comment]
this is a vanilla mc bug

**Comment by ardissaps** [comment]
> this is a vanilla mc bug

well only the bar from this mod have that, I have VanillaTweaks bars fix and it applied to all modded bars including[ CreateDeco](https://www.curseforge.com/minecraft/mc-mods/create-deco), [Charm](https://svenhjol.github.io/Charm/), [AdditionalBars](https://modrinth.com/mod/additionalbars), [Blockus](https://www.curseforge.com/minecraft/mc-mods/blockus). It can be fixed on your side. But thanks anyway going to install it again if it is fixed.
