### ISSUE TITLE
Latest 1.19 Version of the Mod is causing this weird display output on Servers

### ISSUE THREAD

**Issue by xSHXRKIEx** [AstralOrdana/Immersive-Weathering#108]
https://pastebin.com/jiwyceUM
https://cdn.discordapp.com/attachments/989441510552514562/995526979271012433/unknown.png

**Comment by rotgruengelb** [comment]
Can confirm. Restart dos not help.
Messes up:
> Chat messages
> Command Responses 
> System Messages
> Player Joins


![Bildschirmfoto 2022-07-09 um 23 17 54](https://user-images.githubusercontent.com/75038404/178474567-1a0146c1-c22d-4061-b193-1f663db4333e.png)
![Bildschirmfoto 2022-07-09 um 23 10 56](https://user-images.githubusercontent.com/75038404/178474591-98689bd7-9aa5-4170-84cc-8c4a5b12d18f.png)

**Comment by TimestaticYT** [comment]
I have the same issue so I hope this will be resolved

**Comment by guest0431** [comment]
Happens to me as well

**Comment by TigerWalts** [comment]
The mod Jar contains the file `assets/minecraft/lang/en_us.json` with the contents:

```json
{
  "block.minecraft.sand": "Sand Block",
  "block.minecraft.red_sand": "Red Sand Block"
}
```

This is effectively wiping all the aliases for the logger and setting just 2.

Editing the Jar and removing this file will make the server use the default language file.

**Comment by TimestaticYT** [comment]
> The mod Jar contains the file `assets/minecraft/lang/en_us.json` with the contents:
> 
> ```json
> {
>   "block.minecraft.sand": "Sand Block",
>   "block.minecraft.red_sand": "Red Sand Block"
> }
> ```
> 
> This is effectively wiping all the aliases for the logger and setting just 2.
> 
> Editing the Jar and removing this file will make the server use the default language file.

Thanks, this will definitely be helpful

**Comment by rotgruengelb** [comment]
> 

Makes sense 
thanks now the devs just have to fix it

**Comment by rotgruengelb** [comment]
> The mod Jar contains the file `assets/minecraft/lang/en_us.json` with the contents:
> 
> ```json
> {
>   "block.minecraft.sand": "Sand Block",
>   "block.minecraft.red_sand": "Red Sand Block"
> }
> ```
> 
> This is effectively wiping all the aliases for the logger and setting just 2.
> 
> Editing the Jar and removing this file will make the server use the default language file.

Makes sense
thanks now the devs just have to fix it

**Comment by AstralOrdana** [comment]
fixed for upcoming version
