### ISSUE TITLE
Granite generator not properly working and appears to be afected by a lot of factors

### ISSUE THREAD

**Issue by Looxond** [AstralOrdana/Immersive-Weathering#109]
Im using immersive_weathering-1.18.2-1.2.11 along side other mods in a server and for some reason the granite gen is not working as it should after a bit testing i realized of couple of things.

The product of diorite + smooth quartz block is determined by their position, not sure if its the axis or left or right.

![image](https://user-images.githubusercontent.com/29359853/180584913-2b09fa63-7a0d-4d2d-aef7-12423e069468.png)

Ill do another test with other generators to see if its exclusive to granite

**Comment by AstralOrdana** [comment]
fixed for upcoming version
