### ISSUE TITLE
[Suggestion] [1.18.2] Add config option to make leaf piles not slow you down

### ISSUE THREAD

**Issue by artemisSystem** [AstralOrdana/Immersive-Weathering#114]
I would like to suggest adding a config option which when enabled makes leaf piles not slow you down or prevent your jump, since i really dislike how hard it makes manouvering jungles and forests you've lived in for a while

**Comment by AstralOrdana** [comment]
this effect of leaf piles only applies to leaf piles of greater than two layers which do not occur naturally in great ammounts and can only be created by the player from either placing them or by harvesting trees and letting the leaves pile up
