### ISSUE TITLE
Saplings turn into dead bushes.

### ISSUE THREAD

**Issue by Zarepheth** [AstralOrdana/Immersive-Weathering#117]
More specifically, I planted some Acacia saplings and after a while, instead of growing into trees, they turned into dead bushes.

I suppose this lets me gather sticks, but I really wanted the trees.

I'm actually guessing that this mod is responsible, since I've got over 200 mods installed. My second choice guess is Regrowth, I'm doubting other mods would have messed with this mechanic...

**Comment by AstralOrdana** [comment]
that's not a bug, its a feature and it only happens in hot biomes

**Comment by Zarepheth** [comment]
Wait a minute!
I agree, the "Savanna" biome qualifies as "hot", but Acacia trees are native to the biome, they ought to be adapted to the climate!

Will this also impact modded trees that should spawn (and grow from saplings) in "hot" biomes?
Is there a workaround for growing trees in hot biomes?

**Comment by AstralOrdana** [comment]
i'll make acacia saplings immune to it and no, it shouldnt happen to modded saplings and theres no current workaround

**Comment by Zarepheth** [comment]
Thanks for exempting Acacia saplings, when in hot biomes.

If you're making some saplings fail in hot biomes, others should probably fail in cold biomes. I suppose this should be a separate feature request?
