### ISSUE TITLE
[Suggestion] Config for Weed Growth

### ISSUE THREAD

**Issue by cybercat5555** [AstralOrdana/Immersive-Weathering#121]
Fairly straightforward, a way to disable the growth of weeds in untended crops. Sorry if this has already been asked/already exists but I overlooked it

**Comment by AstralOrdana** [comment]
fixed for upcoming version

**Comment by CaptainVianite** [comment]
Sorry to re-open this but I don't believe this was added? I went through the config multiple times and could not find anything relating to disabling weeds.
