### ISSUE TITLE
Iron bar variants lack tag making them transparent to the Encased Fan from Create

### ISSUE THREAD

**Issue by Boxed-catgirl** [AstralOrdana/Immersive-Weathering#123]
Version: Forge 40.1.73
Immersive Weathering 1.2.11
Create 0.5.0d
As is described as of the most recent version of IW and Create, the iron bars variants (all of them, waxed, exposed, weathered, rusted) lack the tag (FAN_TRANSPARENT) making them transparent to the Encased Fan, which makes it so bulk washing, blasting, smoking recipes as well as general airflow doesn’t pass through them. This is really annoying especially with bulk washing as it rusts very fast and waxing the bars also makes them solid.

**Comment by AstralOrdana** [comment]
fixed for upcoming version
