### ISSUE TITLE
...LEAF_DECAY_PARTICLES" is null. (server crash)

### ISSUE THREAD

**Issue by DemonMartin** [AstralOrdana/Immersive-Weathering#130]
[crash-2022-10-05_01.10.38-server.txt](https://github.com/AstralOrdana/Immersive-Weathering/files/9711416/crash-2022-10-05_01.10.38-server.txt)

**Comment by DemonMartin** [comment]
Playing on newest Version (3.0.0  1.18.2, Fabric)

**Comment by DemonMartin** [comment]
Forgot to say but, downgrading to v2.5.6 (1 Version behind 3.0.0) fixed the Issue.

**Comment by AntonIXO** [comment]
Have the same issue on Forge 3.0 version.

**Comment by tokanada** [comment]
Hello,

Sorry to bring up an closed issue, but I'm still having this issue with the newest version of Immersive Weathering in 1.18.2 (3.0.0). 

There appears to be some sort of conflict between Oh The Biomes You'll Go+TerraBlender and Immersive Weathering that's causing my server to crash just like the original post

> [crash-2022-10-05_01.10.38-server.txt](https://github.com/AstralOrdana/Immersive-Weathering/files/9711416/crash-2022-10-05_01.10.38-server.txt)

There are no problems in singleplayer but whenever I connect to a server running these two/three mods together, the server crashes

___

Minecraft Version: 1.18.2

Fabric API: 0.67.0

BYG: 1.4.7

TerraBlender: 1.2.0.126

Immersive Weathering: 3.0.0

**Comment by tokanada** [comment]
> Hello,
> 
> Sorry to bring up an closed issue, but I'm still having this issue with the newest version of Immersive Weathering in 1.18.2 (3.0.0).
> 
> There appears to be some sort of conflict between Oh The Biomes You'll Go+TerraBlender and Immersive Weathering that's causing my server to crash just like the original post
> 
> > [crash-2022-10-05_01.10.38-server.txt](https://github.com/AstralOrdana/Immersive-Weathering/files/9711416/crash-2022-10-05_01.10.38-server.txt)
> 
> There are no problems in singleplayer but whenever I connect to a server running these two/three mods together, the server crashes
> 
> Minecraft Version: 1.18.2
> 
> Fabric API: 0.67.0
> 
> BYG: 1.4.7
> 
> TerraBlender: 1.2.0.126
> 
> Immersive Weathering: 3.0.0

Looks like I just needed to look on Curseforge and not Modrinth for newer versions of Immersive Weathering.
