### ISSUE TITLE
Only plain Mossy Clumps place mossy overlay

### ISSUE THREAD

**Issue by FreshAlacrity** [AstralOrdana/Immersive-Weathering#134]
The Enchanted Golden Mossy Clump and Golden Moss Clump items don't place the mossy overlay that the regular Moss Clump does (although all three will convert a block with a mossy variety).

Running: Forge 40.1.80 with IW 3.0.2, Quark 3.2-358, Supplementaries 1.5.8, and Moonlight Lib 1.17.9

**Comment by FreshAlacrity** [comment]
I checked and this doesn't appear to change when the blocks in question are added to the `immersive_weathering:mossable` tag (although I'm assuming that just the blocks moss will naturally spread onto and the intended behavior I assumed was for all three clumps to allow manual mossing of any suitably shaped block)

**Comment by AstralOrdana** [comment]
this is functioning as intended
