### ISSUE TITLE
Fire on a Grass Block doesn't convert it to Dirt

### ISSUE THREAD

**Issue by FreshAlacrity** [AstralOrdana/Immersive-Weathering#135]
I see support for fire burning over grass blocks to turn them into dirt blocks in the block_growths folder, but using a flint and steel or a fire charge on grass isn't having that effect for me. Is that the intended behavior?

Running Forge 40.1.80 with IW 3.0.2, Quark 3.2-358, Supplementaries 1.5.8, and Moonlight Lib 1.17.9

**Comment by AstralOrdana** [comment]
that is the intended behavior. however, you can use simply flint on grass to convert it to dirt
