### ISSUE TITLE
Fabric versions 3.0.1 and 3.0.2 missing on Modrinth

### ISSUE THREAD

**Issue by Cypher121** [AstralOrdana/Immersive-Weathering#137]
Curseforge ![CurseForge](https://user-images.githubusercontent.com/8020624/194752453-f602a8d7-899a-44ac-9722-3025a04d62e0.png)

vs Modrinth
![Modrinth](https://user-images.githubusercontent.com/8020624/194752479-76b175a0-d49b-4505-ba87-b8164b7dd7d8.png)

**Comment by AstralOrdana** [comment]
this isnt something to open a curseforge issue about
