### ISSUE TITLE
Incompatibility with Consistency+

### ISSUE THREAD

**Issue by Tempest-5ky** [AstralOrdana/Immersive-Weathering#139]
If a player walks on the grass slab or grass stairs from Consistency+ (https://www.curseforge.com/minecraft/mc-mods/consistencyplus), they are kicked from the server and are unable to rejoin.

Minecraft version is 1.18.2, mod version is 3.0.2

Error: https://mclo.gs/TLkF9B3

**Comment by TropheusJ** [comment]
I've left a comment on the C+ issue explaining it. This isn't fixable on our side. https://github.com/ConsistencyPlus/ConsistencyPlus/issues/136

**Comment by AstralOrdana** [comment]
so IW does have a grass -> paths feature but its experimental and disabled by default. this incompatibility has been given a temporary and incomplete fix by just moving the age state check to inside of the config check
