### ISSUE TITLE
Crash on launch [1.19.2 forge]

### ISSUE THREAD

**Issue by EvergreenSystems** [AstralOrdana/Immersive-Weathering#147]
Crash upon startup with the new 1.19.2 forge version

Mod version 1.1.0-forge
Forge version 43.1.32

https://gist.github.com/Shedao-Shai/f853be826430cb6485fa5fe6c544eeca

**Comment by MehVahdJukaar** [comment]
Update Moonlgiht Lib and keep your mods up to date

**Comment by EvergreenSystems** [comment]
Seems that both Moonlight and EveryCompat caused the crash, updating both fixed it
