### ISSUE TITLE
[1.19.2] Crash when right clicking a sand block

### ISSUE THREAD

**Issue by Rosethorns** [AstralOrdana/Immersive-Weathering#151]
**Describe the bug:**
When the player right clicks a sand block the game locks up and closes.

**Versions:**
Minecraft version: 1.19.2
Immersive Weathering version: 1.1.0-forge
Forge version: 43.1.43

**Other mods:**
https://pastebin.com/EzQJHYec
**Logs:**
Please provide the following logs:
[Latest](https://pastebin.com/YGXdRLJc)
no launcher or hs_err, I use AT Launcher. 

**To Reproduce:**
1. Right click sand block

**Expected behavior:**
not to crash when you right click a sand block.

**Comment by AstralOrdana** [comment]
for internal reference: ecologics stripped log bug
