### ISSUE TITLE
Immersive Weathering Crash When Attempting to Strip Bark

### ISSUE THREAD

**Issue by WebP-Official** [AstralOrdana/Immersive-Weathering#153]
**Describe the bug:** When attempting to strip a log block (tested with oak, birch) with an axe (tested with wood, iron), the game will crash to desktop.

**Versions:**
Minecraft version: 1.19.2
Immersive Weathering version: 1.1.1
Fabric API / QSL / Forge version: 43.1.1

**Other mods:**
[https://i.gyazo.com/2accb9db4186822106957bd23e2a2443.png](url)

**Logs:**
[latest.log](https://github.com/AstralOrdana/Immersive-Weathering/files/9823041/latest.log)
[debug.log](https://github.com/AstralOrdana/Immersive-Weathering/files/9823045/debug.log)
[launcher_log.txt](https://github.com/AstralOrdana/Immersive-Weathering/files/9823053/launcher_log.txt)

**To Reproduce:**
Steps to reproduce the behavior. Format it as a numbered list of steps.

1. Select axe in hotbar
2. Right click log block

**Expected behavior:**
Expected behaviour was the stripping of bark as per vanilla mechanic

**Screenshots:**
If applicable, add screenshots to help explain your problem. https://screenshot.help/

**Additional info:**
Add any other information that might be needed.

**Comment by pllot** [comment]
I am getting a similar crash when trying to open a spruce door with a stone axe in hand

**Comment by AstralOrdana** [comment]
can these bugs be reproduced in 1.1.3?

**Comment by pllot** [comment]
> can these bugs be reproduced in 1.1.3?

No just did both with iron axe fine on 1.1.3
