### ISSUE TITLE
Forge Crash on start up (no crash log generated)

### ISSUE THREAD

**Issue by talhanation** [AstralOrdana/Immersive-Weathering#154]
**Describe the bug:**
Crash on start up. Works again after deinstalling your mod.

**Versions:**
Minecraft version: 1.19.2
Immersive Weathering version: 1.1.1
Fabric API / QSL / Forge version: Forge- 43.1.1

**Other mods:**
![Bild_2022-10-19_221215041](https://user-images.githubusercontent.com/10392726/196794132-3cd09f8b-61db-4d3a-934c-b1ff0a02ae44.png)

**Logs:**
[latest.log](https://github.com/AstralOrdana/Immersive-Weathering/files/9823923/latest.log)

**Comment by AstralOrdana** [comment]
can you confirm this for the latest version?
