### ISSUE TITLE
Crashed after playing for a few minutes

### ISSUE THREAD

**Issue by Samapoke** [AstralOrdana/Immersive-Weathering#155]
**Describe the bug:**
After created a new world and started playing for a few minutes, the game freeze and crashed

**Versions:**
Minecraft version: 1.19.2
Immersive Weathering version: 1.1.0
Fabric API / QSL / Forge version: 43.1.43

**Other mods:**
Crash report: https://gist.github.com/Samapoke/1c114fe11f91166529693bc6db05c351

**Logs:**
Latest.log: https://gist.github.com/Samapoke/b1e343ec437c2e61bea5a7838f949048
debug.log: https://gist.github.com/Samapoke/63e5935e4e99ae2b86f58f4390783cd2

**Comment by MehVahdJukaar** [comment]
Update the mod
