### ISSUE TITLE
Crashes with the "Interactic" Mod

### ISSUE THREAD

**Issue by szunakabeats** [AstralOrdana/Immersive-Weathering#157]
**Describe the bug:**
Installed Interactic and Immersive Weathering on Fabric 1.19.2. Went to strip bark off a tree and then it crashes.

**Versions:**
Minecraft version: 1.19.2
Immersive Weathering version: 1.1.2-fabric
Fabric API / QSL / Forge version: Fabric 0.14.9 / API: 0.63.0

**Other mods:**
Mod List in the [Crash Log](https://bytebin.lucko.me/Ofb93D382Z)

**Logs:**
*Even if the game does not crash they may be useful!*
Please provide the following logs:
From .minecraft/logs :  "latest.log" as well as "debug.log" if it exists. From .minecraft : "launcher_log" as well as a
file that starts with "hs_err" if it exists. Note: Double check that the logs are from the correct time. ex, don't give
us a log from a month ago because you forgot to check the date.

[latest.log](https://bytebin.lucko.me/CtwQBDOMX4)  / no debug.log :( / [launcher_log](https://bytebin.lucko.me/LLb89BdHQp)  / no hs_err in the .minecraft folder :/

**To Reproduce:**
Steps to reproduce the behavior. Format it as a numbered list of steps.

1. Make an Fabric 1.19.2 instance
2. Install Immersive Weathering and Interactic
3. Try to strip off bark from a tree

**Expected behavior:**
Bark dropping on the ground as Interactic intends to.

**Screenshots:**

**Additional info:**

**Comment by AstralOrdana** [comment]
can this be reproduced in 1.1.3?

**Comment by lxly9** [comment]
Quite curios, since i use interactic as well but it does not crash for me

**Comment by szunakabeats** [comment]
im testing this after work. i'll let you guys know then

**Comment by AstralOrdana** [comment]
can this be reproduced in 1.1.4?

**Comment by szunakabeats** [comment]
seems to be fixed :). maybe it had something to do with my mod list .. idk :/
