### ISSUE TITLE
(FORGE) Flowering Azalea leaf pile collision crashes game

### ISSUE THREAD

**Issue by Albhis** [AstralOrdana/Immersive-Weathering#160]
**Describe the bug:**
Walking on Flowering Azalea leaf pile crashes the game

Minecraft version: 1.19,2
Immersive Weathering version: 1.1.2
Fabric API / QSL / Forge version: Forge 43.1.1

**Other mods:**

		ecologics-forge-1.19.2-2.1.10.jar |Ecologics |ecologics 
		Fallingleaves-1.19.1-1.3.0.jar |Falling Leaves |fallingleaves

**Logs:**
[latest.log](https://github.com/AstralOrdana/Immersive-Weathering/files/9842455/latest.log)
[crash-2022-10-21_14.55.18-client.txt](https://github.com/AstralOrdana/Immersive-Weathering/files/9842456/crash-2022-10-21_14.55.18-client.txt)

**To Reproduce:**

Walk on a Flowewring Azalea leaf pile 

**Expected behavior:**
I expected regular leaf behavior, since other leaf piles make the other leaves just fine. (Additionally, the Azalea flower pile makes a grey leaf, basically has no values) and does not crash the game for some reason

**Additional info:**
p_104706 is null apparently. I suspect since flowering azalea simply uses the same fallen leaves as azalea leaves

**Comment by AstralOrdana** [comment]
fixed for upcoming version
