### ISSUE TITLE
Weird crash that i don't know how to describe it

### ISSUE THREAD

**Issue by gousisme** [AstralOrdana/Immersive-Weathering#161]
**Describe the bug:**
1 flowering azalea tree on flowing water, leave it for sometimes and the game crashed, I can't join the world anymore

Minecraft version: 1.19.2
Immersive Weathering version: 1.1.2
Fabric API / QSL / Forge version: Forge 43.1.43

**Other mods:**
No other mods installed

**Logs:**
Crash log:
[crash-2022-10-22_09.15.49-client.txt](https://github.com/AstralOrdana/Immersive-Weathering/files/9843359/crash-2022-10-22_09.15.49-client.txt)
Latest.log: 
[latest.log](https://github.com/AstralOrdana/Immersive-Weathering/files/9843361/latest.log)
Debug.log:
[debug.log](https://github.com/AstralOrdana/Immersive-Weathering/files/9843362/debug.log)

**To Reproduce:**
Steps to reproduce the behavior. Format it as a numbered list of steps.

1. Create a new world
2. Spawn a flowering azalea tree with water flowing under it
3. Wait and the game crashes, I've been trying to reproduce this but it rarely happens

**Expected behavior:**
The game runs normally instead of crashing

**Comment by lxly9** [comment]
exact same thing happens on fabric too
