### ISSUE TITLE
Resourcepacks Fail to Load

### ISSUE THREAD

**Issue by lanwoodall423** [AstralOrdana/Immersive-Weathering#165]
**Describe the bug:**
When using Immersive Weathering and this mod set, an error occurs that removes (deactivates) all resourcepacks. This is logged even if only vanilla resourcepacks are enabled. The error references BYG red_maple_leaf. 

**Versions: (BEFORE SUBMITTING A BUG REPORT, make sure you have the most up-to-date versions of Immersive Weathering, Moonlight Lib: 2.1.3
Supplementaries: 2.2.9
Oh The Biomes You'll Go: 2.0.0.13
Minecraft version: 1.19.2
Immersive Weathering version: 1.1.3
Fabric API / QSL / Forge version: 0.63.0

**Other mods:**
- additionaladditions 5.1.0
	- advanced_runtime_resource_pack 0.6.4
	- advancementplaques 1.4.6
	- adventurez 1.4.16
	- almostunified 1.19.2-0.2.0
	- alternate-current 1.4.0
	- ambientenvironment 8.0+3
	- ambientsounds 5.2.5
	- amethyst_core 0.3.3+1.19 via amethyst_imbuement
	- amethyst_imbuement 1.19-15
	- animatica 0.5+1.19
	- another_furniture 2.1.2-1.19.2
	- appleskin 2.4.1+mc1.19
	- archeology 0.2.4
	- architectury 6.2.46
	- areas-fabric 3.2
	- armorchroma 1.2.2
	- armorstatues 4.0.2
	- artifacts 7.1.1+fabric
	- attributefix 17.1.2
	- auditory 0.0.3-1.19.x
	- autoswitch 5.4.4
	- autoswitch-api 3.0.0 via autoswitch
	- autotag 2.0.0+1.19 via autotag-convention
	- autotag-convention 2.0.0+1.19
	- axolotlitemfix 1.1.3
	- balm-fabric 4.5.2+0
	- bambooeverything 2.2.4-build.33+mc1.19.2
	- bclib 2.1.2
	- bendy-lib 2.1.2 via emotecraft
	- betteradvancements 0.2.2.142
	- betteranimalsplus 1.19-11.0.7
	- betteranimationscollection 4.0.4
	- betterbeds 1.2.0
	- bettercombat 1.4.4+1.19
	- betterdeserttemples 1.19.2-Fabric-2.2.1
	- betterdungeons 1.19.2-Fabric-3.2.1
	- betterend 2.1.1
	- betterf3 4.0.0
	- bettermineshafts 1.19.2-Fabric-3.2.0
	- betternether 7.1.1
	- betteroceanmonuments 1.19.2-Fabric-2.1.0
	- betterstats 1.4.3
	- betterstrongholds 1.19.2-Fabric-3.2.0
	- bettertridents 4.0.1
	- betterwitchhuts 1.19.2-Fabric-2.1.0
	- bewitchment 1.19-5
	- biomeinfo 1.19.2-12
	- biomemakeover 1.19.2-1.5.12
	- blanket-client-tweaks 1.1.2
	- blockrunner 4.2.0
	- blue_endless_jankson 1.2.1 via owo
	- boat-with-everything 1.1.0
	- bookshelf 16.1.5
	- bosses_of_mass_destruction 1.4.3-1.19.2
	- brewery 0.2.1+1.19.2
	- bushierflowers 0.0.1-1.19.2
	- bwplus 1.19-5
	- byg 2.0.0.13
	- caffeineconfig 1.0.0+1.17 via sodium-extra
	- cameraoverhaul 1.3.1-fabric-universal
	- cardinal-components 5.0.2
	- cardinal-components-base 5.0.2 via cardinal-components
	- cardinal-components-block 5.0.2 via cardinal-components
	- cardinal-components-chunk 5.0.2 via cardinal-components
	- cardinal-components-entity 5.0.2 via cardinal-components
	- cardinal-components-item 5.0.2 via cardinal-components
	- cardinal-components-level 5.0.2 via cardinal-components
	- cardinal-components-scoreboard 5.0.2 via cardinal-components
	- cardinal-components-world 5.0.2 via cardinal-components
	- catalogue 1.6.3-1.19.2
	- cem 0.7.1
	- charm 4.4.4
	- chat_heads 0.7.1
	- citresewn 1.1.2+1.19.2
	- citresewn-defaults 1.1.2+1.19.2 via citresewn
	- clear-skies 2.0.95
	- cloth-basic-math 0.6.1 via cloth-config
	- cloth-config 8.2.88
	- coat 1.0.0-beta.17+mc22w17a via completeconfig
	- collective-fabric 5.11
	- colormatic 3.1.2+mc.1.19
	- com_electronwill_night-config_core 3.6.6 via byg
	- com_electronwill_night-config_toml 3.6.6 via byg
	- com_eliotlash_mclib_mclib 19 via geckolib3
	- com_eliotlash_molang_molang 19 via geckolib3
	- com_github_llamalad7_mixinextras 0.0.12 via cull-less-leaves
	- com_logisticscraft_occlusionculling 0.0.6-SNAPSHOT via entityculling
	- com_moandjiezana_toml_toml4j 0.7.2 via charm
	- com_sksamuel_scrimage_scrimage-core 4.0.31 via minelib
	- com_velocitypowered_velocity-native 3.1.2-SNAPSHOT via krypton
	- combatroll 1.0.8+1.19
	- completeconfig 2.0.0
	- completeconfig-base 2.0.0 via completeconfig
	- completeconfig-gui-cloth 2.0.0 via completeconfig
	- completeconfig-gui-coat 2.0.0 via completeconfig
	- conditional-mixin 0.3.0 via cull-less-leaves
	- connectiblechains 2.1.3+1.19.2
	- connectivity 1.19-3.3
	- continuity 2.0.1+1.19
	- controlling 10.0+6
	- cosmetic-armor 1.4.0
	- cr-arrows-info 1.2.1+1.19
	- creativecore 2.8.5
	- creaturesofthesnow 3.1.0+1.19.2
	- creeperoverhaul 2.0.3
	- cull-less-leaves 1.0.6
	- customportalapi 0.0.1-beta52-1.19 via deeperdarker
	- damagetilt 1.19-fabric-0.1.2
	- darkness 2.0.98
	- dawn 3.5.0
	- debugify 2.7.1
	- decor4fabric 1.2.1
	- deeperdarker 1.0.2b-fabric
	- detailab 2.6.2+1.19-fabric
	- diagonalfences 4.2.3
	- disableinsecurechattoast 1.1.0
	- discholder 1.3.0
	- display 1.1.0
	- display_case 1.0.3
	- doodads 0.1.2-1.19.2
	- draggable-resource-packs 3.0.1+build.9
	- droplight 1.0.2
	- dyed 1.1.0
	- dynamiccrosshair 3.9+1.19
	- dynamiccrosshaircompat 1.9+1.19.2
	- dynamicfps 2.2.0
	- earthtojavamobs 1.9.3
	- easyanvils 4.0.5
	- ecologics 2.1.10
	- effective 1.4
	- elden_horses 1.0.1+1.19.2
	- eldritch_mobs 1.12.7
	- emotecraft 2.2.5
	- enchdesc 13.0.3
	- enhanced_attack_indicator 1.0.4+1.19
	- entity_texture_features 4.1.1
	- entityculling 1.5.2-mc1.19
	- error_notifier 1.0.9 via roughlyenoughitems
	- exordium 1.0.1-mc1.19.2
	- expandability 6.0.0 via artifacts
	- expandeddelight 0.2.2
	- expert_armor 2.1.7
	- fabric-api 0.63.0+1.19.2
	- fabric-api-base 0.4.12+93d8cb8290 via dynamiccrosshaircompat
	- fabric-api-lookup-api-v1 1.6.10+93d8cb8290 via fabric-api
	- fabric-biome-api-v1 9.0.18+c6af733c90 via fabric-api
	- fabric-blockrenderlayer-v1 1.1.21+c6af733c90 via fabric-api
	- fabric-client-tags-api-v1 1.0.2+b35fea8390 via autoswitch
	- fabric-command-api-v1 1.2.12+f71b366f90 via fabric-api
	- fabric-command-api-v2 2.1.8+93d8cb8290 via fabric-api
	- fabric-commands-v0 0.2.29+df3654b390 via fabric-api
	- fabric-containers-v0 0.1.35+df3654b390 via fabric-api
	- fabric-content-registries-v0 3.3.2+624e468e90 via fabric-api
	- fabric-convention-tags-v1 1.1.2+93d8cb8290 via fabric-api
	- fabric-crash-report-info-v1 0.2.6+aeb40ebe90 via fabric-api
	- fabric-data-generation-api-v1 5.2.1+b598f4ac90 via fabric-api
	- fabric-dimensions-v1 2.1.32+0dd10df690 via fabric-api
	- fabric-entity-events-v1 1.4.19+9ff28f4090 via fabric-api
	- fabric-events-interaction-v0 0.4.29+c6af733c90 via fabric-api
	- fabric-events-lifecycle-v0 0.2.29+df3654b390 via fabric-api
	- fabric-game-rule-api-v1 1.0.22+c6af733c90 via fabric-api
	- fabric-item-api-v1 1.5.8+93d8cb8290 via fabric-api
	- fabric-item-groups-v0 0.3.31+0c4b8d3c90 via fabric-api
	- fabric-key-binding-api-v1 1.0.22+aaaf9d3390 via fabric-api
	- fabric-keybindings-v0 0.2.20+df3654b390 via fabric-api
	- fabric-language-kotlin 1.8.5+kotlin.1.7.20
	- fabric-lifecycle-events-v1 2.2.0+33ffe9ec90 via fabric-api
	- fabric-loot-api-v2 1.1.5+83a8659290 via fabric-api
	- fabric-loot-tables-v1 1.1.8+9e7660c690 via fabric-api
	- fabric-message-api-v1 5.0.4+93d8cb8290 via fabric-api
	- fabric-mining-level-api-v1 2.1.16+33fbc73890 via fabric-api
	- fabric-models-v0 0.3.18+c6af733c90 via fabric-api
	- fabric-networking-api-v1 1.2.5+c6af733c90 via fabric-api
	- fabric-networking-v0 0.3.22+df3654b390 via fabric-api
	- fabric-object-builder-api-v1 4.0.13+93d8cb8290 via fabric-api
	- fabric-particles-v1 1.0.11+79adfe0a90 via fabric-api
	- fabric-permissions-api-v0 0.1-SNAPSHOT via bewitchment
	- fabric-registry-sync-v0 0.9.26+c6af733c90 via fabric-api
	- fabric-renderer-api-v1 1.0.12+c0ae659d90 via fabric-api
	- fabric-renderer-indigo 0.6.14+aeb40ebe90 via fabric-api
	- fabric-renderer-registries-v1 3.2.21+df3654b390 via fabric-api
	- fabric-rendering-data-attachment-v1 0.3.15+aeb40ebe90 via fabric-api
	- fabric-rendering-fluids-v1 3.0.8+c6af733c90 via fabric-api
	- fabric-rendering-v0 1.1.23+df3654b390 via fabric-api
	- fabric-rendering-v1 1.11.0+73145abb90 via fabric-api
	- fabric-resource-conditions-api-v1 2.1.0+aae9039d90 via fabric-api
	- fabric-resource-loader-v0 0.7.1+0c4b8d3c90 via fabric-api
	- fabric-screen-api-v1 1.0.27+93d8cb8290 via fabric-api
	- fabric-screen-handler-api-v1 1.3.1+1cc24b1b90 via dynamiccrosshaircompat
	- fabric-sound-api-v1 1.0.0+c4f28df590 via fabric-api
	- fabric-textures-v0 1.0.21+aeb40ebe90 via fabric-api
	- fabric-transfer-api-v1 2.1.1+93d8cb8290 via dynamiccrosshaircompat
	- fabric-transitive-access-wideners-v1 1.3.1+42d99c3290 via fabric-api
	- fabricloader 0.14.9
	- fake-player-api 0.4.0 via the_bumblezone
	- fallingleaves 1.12.2+1.19.2
	- farmersdelight 1.19-1.3.3
	- farmersknives 2.1
	- fastload 1.2.1
	- ferritecore 4.2.1
	- fiber 0.23.0-2 via collective-fabric
	- forgeconfigapiport 4.2.6
	- friendsandfoes 1.5.11
	- frozenblocklib 1.1.1-Fabric+1.19.2 via wilderwild
	- geckolib3 3.1.26
	- geodes 1.5.1
	- glow_ink_plus 1.0.2-1.19.x
	- go-fish 1.6.0-1.19.1
	- goodall 1.1.1
	- graveyard 2.0
	- highlighter 1.1.4
	- hologram-api 0.2.2+1.19 via brewery
	- horsestatsvanilla 4.2.2
	- iceberg 1.0.46
	- illuminations 1.10.8
	- immersive_paintings 0.3.0+1.19.2
	- immersive_weathering 1.19.2-1.1.3
	- impaled 1.1.4
	- impersonate 2.7.0 via bewitchment
	- incendium 5.1.0
	- indium 1.0.9+mc1.19.2
	- infinitybuttons 2.0.0-mc1.19
	- interactic 0.1.11+1.19
	- inventoryprofilesnext 1.8.2
	- io_github_douira_glsl-transformer 1.0.0-pre21.2 via iris
	- iris 1.4.0
	- itemborders 1.1.6
	- jankson 4.1.1+j1.2.1 via libgui
	- java 17
	- kanos_config 0.3.1+1.14.4-1.19 via pehkui
	- kirin 1.11.1 via presencefootsteps
	- kofitable 1.0.4+1.19.x
	- krypton 0.2.1
	- lambdabettergrass 1.3.0+1.19
	- lazydfu 0.1.3
	- legendarytooltips 1.3.3
	- letmedespawn fabric-1.0.2
	- libgui 6.0.1+1.19 via discholder
	- libipn 1.0.3
	- libninepatch 1.1.0 via libgui
	- lithium 0.10.0
	- lovely_snails 1.1.0+1.19
	- maelstrom_library 1.3-1.19-pre1 via bosses_of_mass_destruction
	- map_atlases 2.1.0
	- mcwbridges 2.0.5
	- mcwdoors 1.0.7
	- mcwfences 1.0.6
	- mcwlights 1.0.4
	- mcwpaintings 1.0.4
	- mcwpaths 1.0.1
	- mcwtrpdoors 1.0.7
	- medievalweapons 1.4.1
	- megaparrot 1.0.7-1.19.2
	- menulogue 1.0.1-1.19.2
	- merchantmarkers 1.2.3
	- midnightlib 0.6.1
	- minecraft 1.19.2
	- minelib 0.1.3+1.19
	- mixin-conflict-helper 1.2.0
	- mm 2.3 via qu-enchantments
	- mob_catcher 1.2.13
	- mobscarecrow 2.2.1-1.19.1
	- modmenu 4.0.6
	- moonlight 1.19.2-2.1.3
	- more-axolotls 1.0.2
	- more_babies 1.0.0
	- more_codecs 0.2.2+1.18 via brewery
	- more_ladders fabric-1.0.1-1.19.2
	- morediscs 1.19.2-22
	- morefrogs 1.19.x-1.2.3-fabric
	- moremcmeta 1.19-3.0.5
	- morevillagers 4.0.2
	- multipart_entities 1.2-1.19-pre1 via bosses_of_mass_destruction
	- musica 1.5.4
	- mythicmounts 1.19.2-7.0
	- naturalist 2.1.1
	- nbtcrafting 2.2.1+mc1.19
	- net_objecthunter_exp4j 0.4.8 via brewery
	- no-resource-pack-warnings 1.0.0
	- no_tutorial_toast 1.0.0
	- notes 1.19.2-2.0.0-fabric
	- nox 2.0.0
	- npcvariety 2.2.2
	- nullscape 1.2
	- omega-config 1.2.2-1.18.1 via graveyard
	- org_anarres_jcpp 1.4.14 via iris
	- org_antlr_antlr4-runtime 4.10.1 via iris
	- org_apache_httpcomponents_httpmime 4.5.10 via entity_texture_features
	- org_javassist_javassist 3.28.0-GA via yungsapi
	- org_jetbrains_kotlin_kotlin-reflect 1.7.20 via fabric-language-kotlin
	- org_jetbrains_kotlin_kotlin-stdlib 1.7.20 via fabric-language-kotlin
	- org_jetbrains_kotlin_kotlin-stdlib-jdk7 1.7.20 via fabric-language-kotlin
	- org_jetbrains_kotlin_kotlin-stdlib-jdk8 1.7.20 via fabric-language-kotlin
	- org_jetbrains_kotlinx_atomicfu-jvm 0.18.4 via fabric-language-kotlin
	- org_jetbrains_kotlinx_kotlinx-coroutines-core-jvm 1.6.4 via fabric-language-kotlin
	- org_jetbrains_kotlinx_kotlinx-coroutines-jdk8 1.6.4 via fabric-language-kotlin
	- org_jetbrains_kotlinx_kotlinx-datetime-jvm 0.4.0 via fabric-language-kotlin
	- org_jetbrains_kotlinx_kotlinx-serialization-cbor-jvm 1.4.1 via fabric-language-kotlin
	- org_jetbrains_kotlinx_kotlinx-serialization-core-jvm 1.4.1 via fabric-language-kotlin
	- org_jetbrains_kotlinx_kotlinx-serialization-json-jvm 1.4.1 via fabric-language-kotlin
	- org_joml_joml 1.10.4 via sodium
	- org_json_json 20211205 via pickyourpoison
	- org_reflections_reflections 0.10.2 via yungsapi
	- owo 0.8.5+1.19
	- packet_tweaker 0.3.0+1.18.2 via polymer
	- patchouli 1.19.2-76-FABRIC
	- peculiarpieces 1.2.13+1.19.x
	- pehkui 3.5.0+1.14.4-1.19.2
	- pickupnotifier 4.2.0
	- pickyourpoison 1.0.9
	- placeholder-api 2.0.0-beta.7+1.19 via brewery
	- player-animator 0.3.5
	- playerabilitylib 1.6.0 via amethyst_imbuement
	- pling 1.5.0
	- polymer 0.2.16+1.19.2 via brewery
	- polymer-registry-sync-manipulator 0.0.3+1.19.2 via polymer
	- presencefootsteps 1.6.2
	- prism 1.0.3
	- probablychests 0.5.5-1.19.2
	- puzzle 1.4.0-1.19
	- puzzle-base 1.4.0-1.19 via puzzle
	- puzzle-gui 1.4.0-1.19 via puzzle
	- puzzle-models 1.4.0-1.19 via puzzle
	- puzzle-splashscreen 1.4.0-1.19 via puzzle
	- puzzleslib 4.3.11
	- qu-enchantments 1.2.4-1.19
	- raised 1.1.3
	- reach-entity-attributes 2.3.0 via bewitchment
	- reeses-sodium-options 1.4.7+mc1.19.2-build.59
	- revelationary 1.0.2
	- rocks 1.6.1
	- rottencreatures 0.1.0
	- roughly_enough_loot_tables 1.19-1.0
	- roughly_enough_trades 1.19-1.0
	- roughlyenoughitems 9.1.554
	- roughlyenoughprofessions 1.1.2
	- roughlyenoughresources 2.6.0
	- satin 1.8.0 via pickyourpoison
	- server_translations_api 1.4.17+1.19.2 via brewery
	- sgui 1.1.5+1.19.1 via brewery
	- simple_shields 1.0.0 - 1.19
	- skinlayers 1.5.2-mc1.19.1
	- skylorlib 1.5.1
	- smoothboot 1.19-1.7.1
	- snowyspirit 1.19.2-2.0.7
	- sodium 0.4.4+build.18
	- sodium-extra 0.4.11+mc1.19.2-build.68
	- soulfired 1.1.0.0
	- spark 1.9.42
	- spiderstpo 2.0.1
	- spruceui 4.0.0+1.19 via lambdabettergrass
	- starlight 1.1.1+fabric.ae22326
	- step-height-entity-attribute 1.0.0 via artifacts
	- steves_vanilla 1.19.2+2.0.1
	- stoneholm 1.4.4
	- strawgolem 2.0.0b2
	- structurized-reborn 1.19-01 via amethyst_imbuement
	- stylisheffects 4.3.2
	- supplementaries 1.19.2-2.2.9
	- tenshilib 1.19-1.6.11
	- terrablender 2.0.1.127
	- terraform-wood-api-v1 4.1.1 via bewitchment
	- terralith 2.3
	- the_bumblezone 6.1.14+1.19.2
	- themissingvillages 2.0.0
	- things 0.2.20+1.19
	- transparent 5.1.2
	- transportables 1.2.1
	- trashslot 12.0.1
	- travelerstitles 1.19.2-Fabric-3.1.0
	- treechop 0.16.1
	- trinkets 3.4.0
	- universal_ores 1.4.2
	- untitledduckmod 0.6.1
	- variant_bookshelves 1.2.1
	- variant_grindstones 1.1.0
	- variantbarrels 2.3
	- variantcomposters 1.0.5
	- variantcraftingtables 3.2.6
	- villagernames 4.0.9
	- visiblebarriers 1.5.3+1.19.x
	- visuality 0.5.1
	- visualoverhaul 4.1.1
	- visualworkbench 4.2.0
	- voidz 1.0.9
	- vsas 2.1.8
	- waterdripsound 1.19-0.3.0
	- waveycapes 1.2.1
	- weaponmaster 3.0.2
	- wilderwild 1.1.1-Fabric+1.19.2
	- wildlife 1.19.2-2.1
	- windchimes 1.2.1
	- xps 0.4.6-r+1.19.2-Fabric
	- xtraarrows 2.0
	- yet-another-config-lib 1.6.0
	- yungsapi 1.19.2-Fabric-3.8.2
	- yungsbridges 1.19.2-Fabric-3.1.0
	- yungsextras 1.19.2-Fabric-3.1.0
	- z_mcwfencesbyg 1.19.2-1.0

**Logs:**
[latest.log](https://github.com/AstralOrdana/Immersive-Weathering/files/9855372/latest.log)

**To Reproduce:**
Launch with the above mod set. Possibly just BYG and Immersive Weathering and pre-reqs.

Result in log:
[17:00:09] [Render thread/INFO]: Caught error loading resourcepacks, removing all selected resourcepacks
java.util.concurrent.CompletionException: java.lang.IllegalStateException: Failed to load description for particle immersive_weathering:byg/red_maple_leaf
	at java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:315) ~[?:?]
	at java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:320) ~[?:?]
	at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1807) ~[?:?]
	at java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1796) ~[?:?]
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373) ~[?:?]
	at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182) ~[?:?]
	at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655) ~[?:?]
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622) ~[?:?]
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165) ~[?:?]
Caused by: java.lang.IllegalStateException: Failed to load description for particle immersive_weathering:byg/red_maple_leaf
	at net.minecraft.class_702.method_18836(class_702.java:281) ~[client-intermediary.jar:?]
	at net.minecraft.class_702.method_18837(class_702.java:228) ~[client-intermediary.jar:?]
	at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1804) ~[?:?]
	... 6 more
Caused by: java.io.FileNotFoundException: immersive_weathering:particles/byg/red_maple_leaf.json
	at net.minecraft.class_5912.method_43043(class_5912.java:20) ~[client-intermediary.jar:?]
	at java.util.Optional.orElseThrow(Optional.java:403) ~[?:?]
	at net.minecraft.class_5912.getResourceOrThrow(class_5912.java:20) ~[client-intermediary.jar:?]
	at net.minecraft.class_5912.openAsReader(class_5912.java:28) ~[client-intermediary.jar:?]
	at net.minecraft.class_702.method_18836(class_702.java:265) ~[client-intermediary.jar:?]
	at net.minecraft.class_702.method_18837(class_702.java:228) ~[client-intermediary.jar:?]
	at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1804) ~[?:?]
	... 6 more

**Expected behavior:**
Resourcepacks remain enabled

**Comment by SurealSulwyn** [comment]
I had the same issue, though I don't use BYG. The "Resource Reload Failed" issue persisted even after I disabled all my mods (and all other resource packs) save for Immersive Weathering and it's dependencies. I got around the issue by extracting the resource packs from the mod and force loading them with Open Loader.

**Comment by Timolino456** [comment]
I'm getting a similar resource reload error but with "java.util.concurrent.CompletionException: java.lang.IllegalStateException: Failed to load description for particle immersive_weathering:traverse/red_autumnal_leaf". It doesn't happen always, though, only after starting the game.

**Comment by magneticflux-** [comment]
Also getting this error with Aurora's Decorations:
```
java.util.concurrent.CompletionException: java.lang.IllegalStateException: Failed to load description for particle immersive_weathering:aurorasdeco/budding_jacaranda_leaf 
```

**Comment by magneticflux-** [comment]
I put a non-emulated method-entry breakpoint on `ParticleEngine::loadParticleDescription` and could view the state of the resource loading when particles try to load. The Immersive Weathering Generated Pack is empty:
![image](https://user-images.githubusercontent.com/9124288/198754434-6d67c787-6ef9-4559-9f94-7d9d4bbb521f.png)

`ParticleEngine` extends `PreparableReloadListener` which means its `reload` method gets called and tries to asynchronously load particle definitions: `CompletableFuture.runAsync(() -> this.loadParticleDescription(resourceManager, resourceLocation, map)`. I suspect Immersive Weathering's (or Moonlight's) `ClientDynamicResourcesHandler` reports async success too soon and other async processes see it before it's populated.

**Comment by AstralOrdana** [comment]
I've been unable to reproduce this issue

**Comment by magneticflux-** [comment]
I was able to reproduce it on 1e268bd5b71f988381ee8db68db0f425381c427a by including Traverse for Fabric 1.19.2 https://modrinth.com/mod/traverse/version/6.0.5 (and TerraBlender) in the `fabric/run/mods/` folder.

**Comment by AstralOrdana** [comment]
okay, we still havent been able to reproduce this ourselves but we think we may have fixed it, if some or all of you could test version 1.1.4 and let us know if it still happens, that'd be great

**Comment by Timolino456** [comment]
Just tried it with 1.1.4 and it's still happening for me, with the same error

**Comment by AstralOrdana** [comment]
Anyone who is experiencing this, could you update your moonlight lib and try to reproduce this?

**Comment by Timolino456** [comment]
Updating Moonlight lib fixed it for me, resourcepacks now load correctly.
