### ISSUE TITLE
Dependency tree is unsatisfiable on Quilt

### ISSUE THREAD

**Issue by hibiii** [AstralOrdana/Immersive-Weathering#167]
**Describe the bug:**
Immersive Weathering manifests as depending on `moonlight`, but Moonlight Lib does not have a published Quilt-compatible version on Modrinth

**Versions:**
Minecraft version: 1.19.2
Immersive Weathering version: 1.1.3
Fabric API / QSL / Forge version: loader 0.17.5 stdlib 4.0.0-beta.17+0.64.0

**Other mods:**
none, this bug is reproducible without any mods

**Logs:**
```
Mods:
  [✔] immersive_weathering-1.19.2-1.1.3-fabric
  [✔] quilted-fabric-api-4.0.0-beta.17+0.64.0-1.19.2
~~~snip~~~
[20:25:06] [main/INFO]: Loading Minecraft 1.19.2 with Quilt Loader 0.17.5
[20:25:06] [main/ERROR]: Incompatible mod set!
org.quiltmc.loader.impl.FormattedException: org.quiltmc.loader.impl.discovery.ModSolvingException: Unhandled error involving mod 'Immersive Weathering' (immersive_weathering) v1.19.2-1.1.3:
Dependency for mod 'immersive_weathering' on moonlight versions [>=1.19.2-2.1.0] (0 valid options, 0 invalid options)
	at org.quiltmc.loader.impl.QuiltLoaderImpl.load(QuiltLoaderImpl.java:214) ~[quilt-loader-0.17.5.jar:?]
```

**To Reproduce:**

1. Have a Minecraft instance with Quilt loader
2. Install Immersive Weathering
3. Look for Moonlight Lib but forego it by presuming it's Forge-only helpers
4. Run the game

**Expected behavior:**
The game launching.

**Comment by AstralOrdana** [comment]
this isnt a bug report, its a request to port moonlight lib to quilt

**Comment by hibiii** [comment]
How so? How can you possibly be using moonlight on a platform it does not support? This is a spurious dependency, it should not be there.

**Comment by MehVahdJukaar** [comment]
So does this mean moonlight crashes on quilt? Send a crash report on its GitHub then

**Comment by hibiii** [comment]
moonlight does not crash on quilt because there's no quilt or fabric version. the quilt loader itself complains about the dependency. this has been a feature in fabric for many years, and quilt just inherited it.

**Comment by MehVahdJukaar** [comment]
https://www.curseforge.com/minecraft/mc-mods/selene/files
Mod is here as it always has been
