### ISSUE TITLE
Bewitchment Bark Overridden

### ISSUE THREAD

**Issue by Keoxxa** [AstralOrdana/Immersive-Weathering#169]
When stripping logs with bewitchment installed, the bark type is immersive weathering which can't be used for bewitchment crafting, locking a lot of early and major crafting recipes out.

A quick fix would be to add a crafting recipe for the bark when bewitchment is installed to swap them out.
Or adding a label "bewitchment:barks" to the immersive weathering barks.

Thanks for reading! Hopefully compatibility can be added soon.

This was found using the latest versions of both mods via curseforge.
immersive_weathering-1.19.2-1.1.3-fabric.jar
bewitchment-1.19-6.jar

**Comment by Keoxxa** [comment]
Nevermind I'm stupid, the stripping is meant to be done with athame for the bewitchment bark not an axe.

**Comment by Daddy-Gambit** [comment]
Thank you I'm also stupid.

**Comment by Daddy-Gambit** [comment]
> Nevermind I'm stupid, the stripping is meant to be done with athame for the bewitchment bark not an axe.

Thank you, I'm also stupid.
