### ISSUE TITLE
Nigh-impossible to obtain ash layer block due to charring overriding 100% of the time

### ISSUE THREAD

**Issue by Synthestra** [AstralOrdana/Immersive-Weathering#170]
**Describe the bug:**
As shown here: https://github.com/AstralOrdana/Immersive-Weathering/blob/19b8b929b72d9225d28ab45aa1864a942b5a9b9f/common/src/main/java/com/ordana/immersive_weathering/WeatheringHelper.java#L217
charChance is only checked if not 0 for it to turn into a charred block, which, without modifying the config, is 100% of the time. The only way for "BlockState charred" to not turn into a charred block, if it is an unknown flammable block listed in the "getCharredState(state)" method - then, and only then, it can pass the "(charred == null)" check.

Minecraft version: 1.18.2 + 1.19.2
Immersive Weathering version: 1.18.2-3.0.2-forge
Fabric API / QSL / Forge version: Forge 40.1.80

Removed the below's questions since the issue in iw's code was found so we know the root cause

**Comment by AstralOrdana** [comment]
the `main` branch of iw is no longer being developed and neither is any 1.18 version, we only have the time to maintain 1.19 for fabric and forge and this does not appear to be an issue on that version
