### ISSUE TITLE
Critical Injection Error on launch

### ISSUE THREAD

**Issue by Pralidoxime** [AstralOrdana/Immersive-Weathering#175]
**Describe the bug:**
On startup it fails to launch the game due to a critical injection error

**Versions:)**
Minecraft version: 1.19.2 Fabric
Immersive Weathering version: 1.19.2-1.1.4-fabric
Fabric API / QSL / Forge version: Fabric 0.14.10

**Log:**
[message.txt](https://github.com/AstralOrdana/Immersive-Weathering/files/9926983/message.txt)

**Comment by AstralOrdana** [comment]
update moonlight lib

**Comment by Pralidoxime** [comment]
Downloaded version 2.1.4 fabric and it gives the same error
