### ISSUE TITLE
Permafrost and Cryosol are generated in non-snowy biomes

### ISSUE THREAD

**Issue by woalk** [AstralOrdana/Immersive-Weathering#177]
**Describe the bug:**
When generating a new world using the newest version of Immersive Weathering (v1.1.4) on Fabric, patches of Permafrost, Icicles and Cryosol are generated in a lot of biomes they shouldn't be, including `minecraft:taiga`, `minecraft:old_growth_pine_taiga`, etc. - basically all biomes that are cool, but not snowy.

Previous versions of Immersive Weathering (v1.0.1) did not generate Permafrost and Cryosol in these biomes.

This happens both with and without other mods than Immersive Weathering.
When other mods like Oh The Biomes You'll Go are added, Permafrost, Icicles and Cryosol also generate in a lot of their biomes where it shouldn't, like in maple tree biomes.

**Versions:**
Minecraft version: 1.19.2
Immersive Weathering version: 1.1.4
Moonlight Lib version: 2.1.4
Fabric API version: 0.64.0

**Other mods:**
None (see description)

**Logs:**
[latest.log](https://github.com/AstralOrdana/Immersive-Weathering/files/9942030/latest.log)

**To Reproduce:**
Steps to reproduce the behavior. Format it as a numbered list of steps.

1. Create world and `/locate` cool (but not snowy) biome.

**Expected behavior:**
Cool (but not snowy) biome should not have patches of Permafrost and Cryosol.

**Additional info:**
This might be a problem with how the Permafrost, Icicles and Cryosol features are placed in regards to climate tags - taking all "cool" biomes, instead of all "snowy" biomes.

**Comment by AstralOrdana** [comment]
fixed for future version
