### ISSUE TITLE
Reduce rate of tree growth from leaf piles

### ISSUE THREAD

**Issue by Derpford** [AstralOrdana/Immersive-Weathering#186]
**Feature:**

A configuration option to reduce the rate of tree growth from leaf piles would be really nice. Forests are growing way too fast, turning villages near forests into impossible-to-traverse dense woodland.

**Alternatives:**

Another feature that might help with this is a "trampling" mechanic for leaf piles, where entities moving through leaf piles may reduce them by one level (or remove them outright if the leafpile was at minimum level).

The "Pile Formation Chance" config option seems like it should help with this, but it's already set to `0.005`, or 0.5%. Is this per tick? If so, it may make more sense to have this check run once per second. Likewise, if it's per leaf block, it may be worth changing this behavior--maybe picking a single leaf block per chunk to check each tick. Whatever the current situation is, clearly there's just too many checks for leaf pile generation for Pile Formation Chance to function as expected.

**Additional info:**

**Comment by AstralOrdana** [comment]
"impossible-to-traverse dense woodland"
![image](https://user-images.githubusercontent.com/62686557/201994754-bc4217a1-ba09-48fc-bade-42204b8bf78f.png)

**Comment by AstralOrdana** [comment]
this is the maximum density leaf piles will ever get, unless i misinterpret your issue

**Comment by Derpford** [comment]
I've had to clear trees out of this village repeatedly. It's become less of a problem now that I've turned leaf pile generation down to 0.001, and all of the villagers here died because I got a little too close while under Bad Omen--but on the default settings, trees were growing right in the middle of the village roads and blocking villagers into their houses.
![2022-11-15_14 57 33](https://user-images.githubusercontent.com/10187719/202042373-e44cba6e-1985-4715-ab9d-f53eff35aa1e.png)
![2022-11-15_14 57 14](https://user-images.githubusercontent.com/10187719/202042387-e50c23ce-8646-4795-9747-9e8e4c0da928.png)
![2022-11-15_14 55 40](https://user-images.githubusercontent.com/10187719/202042409-c58d6c90-9cb8-45ec-9c81-01cdae4c272a.png)

**Comment by AstralOrdana** [comment]
please specify which version you are playing because in the latest version, saplings will only spontaneously appear on *rooted grass* and thats the only way iw would be causing random tree growth

**Comment by Derpford** [comment]
I am running Immersive Weathering version `1.18.2-3.0.2`.

**Comment by AstralOrdana** [comment]
that version is outdated and no longer supported
