### ISSUE TITLE
Config addition for improving performance

### ISSUE THREAD

**Issue by Rad586** [AstralOrdana/Immersive-Weathering#189]
Game version: 1.18.2 fabric
Mod version: 3.0.2
**Feature:**
Some config addition for improving performance.

**Additional info:**
I've already tried to disable some feature to improve performance, but it doesn't work as I expected...
Here's a profile generated by spark: https://spark.lucko.me/qOsD94zufk (Running in heavily modded environment)

**Comment by AstralOrdana** [comment]
outdated versions are no longer supported
