### ISSUE TITLE
Many blocks and items display in the wrong creative tabs

### ISSUE THREAD

**Issue by 0Navis0** [AstralOrdana/Immersive-Weathering#191]
Currently display in building tab instead of decoration tab:
- Stone, mossy stone, cracked stone, mossy brick, cracked brick, cracked blackstone, cracked deesplate walls
- Charred fence and fence gate
- Iron doors, trapdoors, bars
- Frosty glass pane
- Fulgurite
- Frosty grass and fern
- Ivy
- Soot

Currently display in building tab instead of miscellaneous tab:
- Ash 
- Sand and red sand

**Versions:**
Minecraft version: 1.19.2
Immersive Weathering version: 1.2.4
Moonlight Lib version: 2.1.10
Forge version: 43.1.52

**Comment by AstralOrdana** [comment]
not planned. 1.19.3 will overhaul the creative menus anyway so its not worth updating a depreciated system
