### ISSUE TITLE
Incorrect Assumption being made in MulchBlock

### ISSUE THREAD

**Issue by KingLemming** [AstralOrdana/Immersive-Weathering#200]
**Describe the bug:**
Lines 99-100 in MulchBlock (Forge, 1.18.2) are making an incorrect assumption that any CropBlock has the default AGE property and also the default maximum age. There are getters for BOTH of these - please use them.

Failing to use them results in a hard server crash if any crop has overridden them.

**Comment by AstralOrdana** [comment]
this was fixed in a newer version of the mod for 1.19, we dont have the time or ability to support 1.18 anymore

**Comment by KingLemming** [comment]
It's a 2-line fix. Do you need me to PR it? Because it'll take like 5 minutes.

**Comment by AstralOrdana** [comment]
Its not that we dont know how to fix it, its just a hassle to re-open all the old code and upload a new jar to curseforge and modrinth.

**Comment by AstralOrdana** [comment]
I can try to find a bunch of 1.18 bugs to fix all at once and hopefully get it out within a week or two, till then quarantine your mulch.

**Comment by KingLemming** [comment]
It sounds like you may need some help with your build process if it's a giant hassle to push a new build out. I'd be happy to help on that front as well.
