### ISSUE TITLE
Client crash when crafted bricks (the material) occupies more space than the inventory has

### ISSUE THREAD

**Issue by Flaguna2** [AstralOrdana/Immersive-Weathering#202]
**Describe the bug:**
Whenever you craft bricks of any type with shift-click (the material, not the block) through the stonecutter, if they're meant to occupy more space than the inventory has, the game will freeze then crash after a few seconds.
Example: 
![image](https://user-images.githubusercontent.com/86506105/206862339-a1220edd-40fd-4a64-9acf-36ddba1f2c23.png)

Notice how I got 3 free inventory spaces, and the ending result will be 4 stacks of bricks, theoretically occupying 4 inventory spaces. If I shift-click to craft these bricks, the game will crash.

**Versions:
Minecraft version: 1.19.2
Immersive Weathering version: 1.2.5 Fabric
Moonlight Lib version: 2.1.15 Fabric
Fabric API / QSL / Forge version: Fabric 0.11.1

**Other mods:**
Will be listed in the crash report below.

**Logs:**

crash-report: [crash-2022-12-10_12.29.55-client.txt](https://github.com/AstralOrdana/Immersive-Weathering/files/10200367/crash-2022-12-10_12.29.55-client.txt)
latest.log: [latest.log](https://github.com/AstralOrdana/Immersive-Weathering/files/10200368/latest.log)
no debug.log

launcher_log: none
hs_err: none

**To Reproduce:**
Steps to reproduce the behavior. Format it as a numbered list of steps.

1. Pick any stack of block that's able to be crafted into the bricks material and place it into the stonecutter. eg.: cobblestone, deepslate
2. have your inventory filled, any amount of filled spaces higher than the amount of bricks crafted works (eg.: you'll craft 8 stacks of bricks, have 7 or lower free inventory spaces.
3. shift-click to craft
4. crash

**Expected behavior:**
Dunno to be honest. Maybe throw the excess crafted bricks on the ground?

**Screenshots:**
up above

**Additional info:**
none.

**Comment by AstralOrdana** [comment]
vanilla issue

**Comment by Flaguna2** [comment]
wasnt expecting that. Thanks for the quick response tho!
