### ISSUE TITLE
[Major Issue] Incompatibility with with any season change mods and visual glitch on public server

### ISSUE THREAD

**Issue by emibanana** [AstralOrdana/Immersive-Weathering#208]
**Describe the bug:**
Few issues please be active on fixings PLEASE, it's a good mod and we hope you continue to maintain them:
- this mod isn't compatible with any mod that implements seasonal changes, during winter, icicle forms, blocks that exposed snow will turn into snowy blocks, however you did not implement a method to revert those blocks back to it's original state during summer, it's kinda dumb, it's literally griefing every block in the world.  Also icicles never melt once they form, so you can see icicle everywhere across the world if you play long enough on a server that has season mod install (for example, medieval MC fabric modpack)
- chopping a tree down and the leaves quickly turn into falling leaves piles, this is an awsome feature! however on a server it will cause a visual glitch, a lot of leaves blocks will stay in mid air and never decay, see below video: (https://youtu.be/X0_fBzt7He4). BUT, this is just a client side visual glitch, all those leaves blocks are actually ghost blocks, and the glitch will be fixed once you reload the chunk by leaving the server and rejoining/leaving the chunk and come back/simply punch them.

**Versions: immersive_weathering-1.19.2-1.2.5-fabric.jar and yes i have all dependencies installed
Minecraft version: 1.19.2
Immersive Weathering version: immersive_weathering-1.19.2-1.2.5-fabric.jar
Moonlight Lib version: 
Fabric API / QSL / Forge version:

**Other mods:**
I am playing and maintaining a medieval mc modpack server, the mods that possibly interact with tree behaviours are:
- falling tree mod (https://www.curseforge.com/minecraft/mc-mods/falling-tree)
- leaves be gone, however tested without this mod and the glitch presist (https://www.curseforge.com/minecraft/mc-mods/leaves-be-gone)
Mod that adds seasonal changes:
- Fabric Season

**Logs:**
no need, check video

**To Reproduce:**
Steps to reproduce the behavior. Format it as a numbered list of steps.
as per discription above

**Expected behavior:**
- snowy blocks can melt during summer/if placed at non-winter biome
- smooth non-glitchy tree chopping experience on server

**Screenshots:**
video providede above

**Additional info:**
N/A

**Comment by emibanana** [comment]
@AstralOrdana can you please be active on resolving issue please

**Comment by MehVahdJukaar** [comment]
This is a feature request

**Comment by emibanana** [comment]
> This is a feature request

I mean if blocks can turn into snowy blocks and can never turn back, that sounds like a missing important feature. It's actually a griefing behavior

another simple solution is provide a switch in the config to turn auto-generating of icicle and snowy blocks off

i tried set "block growth" in the config to false but this is still happening

**Comment by AstralOrdana** [comment]
Its not a griefing behavior if you have a different mod that causes the blocks to change in places they weren't intended to. We can't be expected to account for the changes made by every other mod.

**Comment by MehVahdJukaar** [comment]
They can turn back just as snow, which can spawn and melt with light. As for the block growth config might be a bug as it should turn all of them off. Might also be mis remembering things and that could have its own config

**Comment by emibanana** [comment]
Sounds reasonable, it's a feature request then.

I also see people has mentioned this feature back in 2021 so Im panicking this "feature" will never be added

**Comment by emibanana** [comment]
it's also better if there is some code comments in the config file. majority of the config lines are straight forward however things like "icicle, "spawn_rarity": 12", im not sure what's the unit of the number here?

![image](https://user-images.githubusercontent.com/120373920/207987034-d6dbe15a-7899-4eb3-a8ec-9e8d997a9607.png)

**Comment by MehVahdJukaar** [comment]
Yeah I know but it's one of those things that requires a lot of work and rethink with things like a streamlined internal temperature system. There are plans for this and I actually already have code for both loaders season mods but we are both busy now and so idk when it will be worked on

**Comment by MehVahdJukaar** [comment]
For the config JSON doesn't support them. On forge it uses its toml which had them and on fabric you are supposed to use a config GUI mod anyways (forge too tbh)

**Comment by emibanana** [comment]
> 

you mean this is the reason why setting "block growth" to false not seems fixing the issue?

**Comment by MehVahdJukaar** [comment]
Yes because it has its own config

**Comment by MehVahdJukaar** [comment]
Which you just posted

**Comment by emibanana** [comment]
Not sure what you mean still... BUT, does it mean this can never be turn off?

**Comment by MehVahdJukaar** [comment]
It has its own config implies that the config does something which affects it. That's what they are made for. If you would have followed my instructions and used cloth config or yacl to access the comments you would have figured it out already

**Comment by emibanana** [comment]
> It has its own config implies that the config does something which affects it. That's what they are made for. If you would have followed my instructions and used cloth config or yacl to access the comments you would have figured it out already

uh sorry i been searching but i dont see a clear instruction how to manipulate immersive weathering's bahavior using cloth config?

**Comment by MehVahdJukaar** [comment]
Just open the mod config menu ingame

**Comment by emibanana** [comment]
Hey can i ask what does  
 "leaf_piles": {
    "leaf_piles_slow": true,

do?

**Comment by emibanana** [comment]
@MehVahdJukaar

**Comment by MehVahdJukaar** [comment]
Leaf piles slow makes it so when you step on a leaf pile you get slow

**Comment by emibanana** [comment]
thanks, hey happy new year, sorry for troubling previously but I still cant figure out how to fix the server and client side ghost block desync when chopping down a tree, this gets annoying when we doing tree farms on a server.

this might be an interaction with falling tree mod we have in this modpack?

**Comment by emibanana** [comment]
@AstralOrdana 

please, also if you turn on "snow melt on warn biome" this just cause snow melting everywhere in the world (a modded world tbh), I assume you just added a list of vanilla biome that snow wont melt? this shouldnt be coded in this way, it just makes the mod so hard to be integrated into other mods

**Comment by emibanana** [comment]
@MehVahdJukaar

**Comment by emibanana** [comment]
ok looks like its another mod that cause snow melt, disgregard then, but the ghost block due to falling leaves piles is very annoying please fix

**Comment by emibanana** [comment]
> 

this also doesnt work as we are running a modpack on a dedicated server.

If your mod does not even want to follow the mod config, I dont know what to say

**Comment by emibanana** [comment]
@MehVahdJukaar @AstralOrdana 

When can you at least put in a config to disable those annoying snowy blocks, why the fuck is that so hard?????????????????????????????????????????????????????

**Comment by MehVahdJukaar** [comment]
How nice

**Comment by GodsTitan** [comment]
Sorry you had to deal with people like [emibanana](https://github.com/emibanana). Have you put any thought into this feature and or plan on bringing it to this mod?
