### ISSUE TITLE
Incompatibility with Optifine

### ISSUE THREAD

**Issue by l3rimstone** [AstralOrdana/Immersive-Weathering#223]
When loading a world with both optifine and IW in the mods folder, the game will freeze and then crash before it can start to load chunks. 
logs don't reveal anything useful.
crash log found here:
[crash-2023-01-03_19.09.46-server.txt](https://github.com/AstralOrdana/Immersive-Weathering/files/10340981/crash-2023-01-03_19.09.46-server.txt)

when the same world is loaded without optifine in the mod folder, it loads as normal with IW fully functional.

I am using the forge version of the mod.

the only things in my mods folder were IW 1.18.2-3.0.2 and OptiFine 1.18.2 H7

**Comment by emibanana** [comment]
no one use optifine anymore
