### ISSUE TITLE
Disabling world gen features (humus, fluvisol, etc)

### ISSUE THREAD

**Issue by Swagboi7** [AstralOrdana/Immersive-Weathering#225]
For whatever reason, there's no proper way to truly disable certain features in this mod. The 1.18 release does have a config menu for this but it's been proven to be useless. I'd like to see an actual way to disable these in order to prevent overlays with other mods that have versions of these that some people prefer over this one, like the humus in Verdure.

**Comment by AstralOrdana** [comment]
use a datapack
