### ISSUE TITLE
[1.18.2 Forge] - Crash from incorrect crop growth on hydrated mulch

### ISSUE THREAD

**Issue by scalyhat** [AstralOrdana/Immersive-Weathering#228]
Some modded crops (tested on Tomatoes from Farmer's Delight) will crash the game when a hydrated Mulch block attempts to increase their growth stage.

Versions:
Minecraft 1.18.2
Immersive Weathering 3.0.3
Moonlight 1.17.9
Forge 40.2.0
...
Farmer's Delight 1.2.0
(other mods you can see in the crash log dump, but they were not mentioned in the stacktrace)

Logs:
Latest: https://gist.github.com/danlizard/aa51f8f4a437bace736c85746f320ea6
Debug: https://gist.github.com/danlizard/9f5ef4da585bfe74b4f180907b14459b
Crash: https://gist.github.com/danlizard/e87c7653f2562ef109f2c5cd780f3a7b

To reproduce:
1. Place Mulch
2. Hydrate it
3. Plant Tomato Seeds on said Mulch

Expected:
Tomato grows a bit quicker

Happens:
Game freezes

I recommend upping the random tick speed to observe it quickly every time.
If this is an issue I should instead bring to the Farmer's Delight Github, please tell me so.

**Comment by AstralOrdana** [comment]
duplicate report
