### ISSUE TITLE
please make snowy stone blocks melt back to normal!

### ISSUE THREAD

**Issue by Inversil** [AstralOrdana/Immersive-Weathering#237]
**Feature:**

In cold biomes stone blocks get a snowy texture. However, even after the snow melts they still remain snowy.
It would be good if the blocks randomticked back to their original variants as this would ensure streamlined gameplay and better compatibility with a variety of season mods.
It should be really simple to implement I think.

**Alternatives:**

A configuration toggle to disable snowy stone blocks, or just more modularity and configurability in general.

Thank you so much for the amazing mod!!

**Comment by Reshy** [comment]
This is also an issue with Mossy Stone.  You cannot break it, smelt it, or scrape it to get regular stone or cobblestone.

**Comment by SusuPoofyPants** [comment]
I agree about the snowy blocks. The snowy stone stairs are quite pretty but it's weird that they stay like that all year round. The icicles are another issue along exactly the same vein. Icicles all over the trees in summer is weird.

I've had to use a datapack to prevent snowy blocks forming altogether, which is a shame. Currently looking for one that prevents the icicles too, also disappointing. I would much prefer to have them, just during winter only. The Block Blacklist section in configuration doesn't seem to do anything.

I disagree about the mossy stone though. That one makes sense to me.
Edit: @Reshy according to the changelog, u can use flint & steel to remove the moss and the moss won't grow back
