### ISSUE TITLE
Add configuration options

### ISSUE THREAD

**Issue by AstralOrdana** [AstralOrdana/Immersive-Weathering#25]
For enabling and disabling all potentially controversial features and for variables like the time it takes something to weather.

**Comment by ExDrill** [comment]
Could this possibly extend to disabling iron rusting as a mechanic?

**Comment by AstralOrdana** [comment]
we will make as many things configurable as we reasonably can

**Comment by MehVahdJukaar** [comment]
Added on forge

**Comment by AstralOrdana** [comment]
completed for version 2.5.0
