### ISSUE TITLE
Add bark for the nether logs

### ISSUE THREAD

**Issue by RandomGuy91** [AstralOrdana/Immersive-Weathering#250]
read the title :)

**Comment by AstralOrdana** [comment]
![image](https://user-images.githubusercontent.com/62686557/223321042-2ee8a4bc-42a9-4122-8c79-56ee3248de4c.png)

play the mod before making feature requests :)

**Comment by RandomGuy91** [comment]
I did, I actually played with it for a long time. I searched for 'bark' in the creative menu and it didn't show. Are they called something else? (I'm plaing on 1.18.2  mod version 3.0.3 btw)
