### ISSUE TITLE
Missing textures for sandy and snowy walls

### ISSUE THREAD

**Issue by TheLotlaxo** [AstralOrdana/Immersive-Weathering#251]
Missing textures for sandy and snowy stone brick, cobblestone, and stone wall blocks

**Comment by szunakabeats** [comment]
same here

![Screenshot 2023-03-14 213413](https://user-images.githubusercontent.com/88375166/225130162-a9204e29-dbc6-47ab-bf9b-542b98ed6cd9.png)

**Comment by AstralOrdana** [comment]
this is caused by the biome tinted mossy stones built-in resource pack, disable that for temporary fix

**Comment by szunakabeats** [comment]
Alright thanks ! :)

**Comment by rewar8** [comment]
can confirm this works, that I found this from just a google search after trying so many things, **sigh**

**Comment by AstralOrdana** [comment]
fixed for next update
