### ISSUE TITLE
Rooted Dirt can delete any block when bonemealed

### ISSUE THREAD

**Issue by StellaBiscuit** [AstralOrdana/Immersive-Weathering#266]
**Describe the bug:**
When bonemealing rooted dirt, side roots and hanging roots spawn and it doesn't check if a block is hear, deleting it

**Versions: (BEFORE SUBMITTING A BUG REPORT, make sure you have the most up-to-date versions of Immersive Weathering, Moonlight Lib and Supplementaries)**
Minecraft version: 1.19.2
Immersive Weathering version: 1.2.9
Moonlight Lib version: 2.2.29
Fabric API / QSL / Forge version: Fabric - 0.14.19 | Api - 10.76.0

**Other mods:**
Squat Grow (bonemeal when sneaking)

**Logs:**
*Even if the game does not crash they may be useful!*
The log doesn't show anything related to it

**To Reproduce:**
Steps to reproduce the behavior. Format it as a numbered list of steps.

1. Place a rooted dirt
2. Place blocks on the side or under it
3. Bonemeal
4. Profit

**Expected behavior:**
It should not replace the block

**Screenshots:**
Before Bonemealing
![image](https://user-images.githubusercontent.com/53101126/232254311-37961b55-8617-4c81-8e28-a8a7f5066795.png)

After Bonemealing
![image](https://user-images.githubusercontent.com/53101126/232254319-2ec3665a-9a30-4d94-a733-d94f78cd995c.png)

**Additional info:**
Add any other information that might be needed.

**Comment by AstralOrdana** [comment]
lol

**Comment by AstralOrdana** [comment]
fixed for next version
