### ISSUE TITLE
Custom cobblestone generator doesnt work in compact design

### ISSUE THREAD

**Issue by SLimeyMC** [AstralOrdana/Immersive-Weathering#267]
I wanted to make andesite generator for my andesite alloy farm but it seems to not work with the compact staircase. But it does work with the one shown in the wiki.
[latest.log](https://github.com/AstralOrdana/Immersive-Weathering/files/11297670/latest.log)
![2023-04-21_23 40 32](https://user-images.githubusercontent.com/67197922/233690313-6dc02bc6-6c2f-43bd-a7b4-b8b9b25c27e6.png)

**Comment by AstralOrdana** [comment]
this is just the nature of how of how mc fluids and waterlogging works, you'll need to have extra space for the water to be able to flow unfortunately
