### ISSUE TITLE
Mossy stone drops mossy cobblestone when mined with silk touch

### ISSUE THREAD

**Issue by StefanH-AT** [AstralOrdana/Immersive-Weathering#271]
**Describe the bug:**
Mossy stone blocks drop mossy cobblestone when mined with a silk touch pickaxe. I expected it to drop the mossy stone block directly to keep the functionality of silk touch inline with the rest of the game

**Versions:**
Minecraft version: 1.19.2
Immersive Weathering version:1.2.9
Moonlight Lib version: 2.2.29
Fabric API / QSL / Forge version: 0.76.0+1.19.2

**Other mods:**
[Just Enough Farmer's Recipes (by Anxxitty__)](https://www.curseforge.com/minecraft/mc-mods/farmers-delight-jei-plugin)
    [Carry On (by Tschipp)](https://www.curseforge.com/minecraft/mc-mods/carry-on)
    [Just Enough Resources (JER) (by way2muchnoise)](https://www.curseforge.com/minecraft/mc-mods/just-enough-resources-jer)
    [Plushie Mod (by Link_911)](https://www.curseforge.com/minecraft/mc-mods/plushie-mod)
    [Puzzles Lib [Forge & Fabric] (by Fuzs)](https://www.curseforge.com/minecraft/mc-mods/puzzles-lib)
    [Fog Looks Good Now [Fabric] (by itsmineblock11)](https://www.curseforge.com/minecraft/mc-mods/fog-looks-good-now-fabric)
    [MidnightLib (by TeamMidnightDust)](https://www.curseforge.com/minecraft/mc-mods/midnightlib)
    [Cultural Delights [Fabric] (by MrSterner_)](https://www.curseforge.com/minecraft/mc-mods/cultural-delights-fabric)
    [GeckoLib (by Gecko)](https://www.curseforge.com/minecraft/mc-mods/geckolib)
    [YUNG's Better Dungeons (Fabric) (by YUNGNICKYOUNG)](https://www.curseforge.com/minecraft/mc-mods/yungs-better-dungeons-fabric)
    [BetterNether (by Quiqueck)](https://www.curseforge.com/minecraft/mc-mods/betternether)
    [Phosphor (Fabric) (by jellysquid3_)](https://www.curseforge.com/minecraft/mc-mods/phosphor)
    [Structory: Towers (by botanydev)](https://www.curseforge.com/minecraft/mc-mods/structory-towers)
    [Infinity Buttons (by LarsMans)](https://www.curseforge.com/minecraft/mc-mods/infinity-buttons)
    [MaLiLib (by masady)](https://www.curseforge.com/minecraft/mc-mods/malilib)
    [Naturalist (by Starfish_Studios)](https://www.curseforge.com/minecraft/mc-mods/naturalist)
    [Macaw's Doors (by sketch_macaw)](https://www.curseforge.com/minecraft/mc-mods/macaws-doors)
    [WorldEdit CUI (Fabric) (by me4502)](https://www.curseforge.com/minecraft/mc-mods/worldeditcui-fabric)
    [Moonlight Lib (by MehVahdJukaar)](https://www.curseforge.com/minecraft/mc-mods/selene)
    [YUNG's Better Strongholds (Fabric) (by YUNGNICKYOUNG)](https://www.curseforge.com/minecraft/mc-mods/yungs-better-strongholds-fabric)
    [Runes [Fabric] (by daedelus_dev)](https://www.curseforge.com/minecraft/mc-mods/rune-crafting)
    [Overweight Farming (by agentmhkskg)](https://www.curseforge.com/minecraft/mc-mods/overweight-farming)
    [BCLib (by Quiqueck)](https://www.curseforge.com/minecraft/mc-mods/bclib)
    [BetterEnd (by Quiqueck)](https://www.curseforge.com/minecraft/mc-mods/betterend)
    [Easy Anvils [Forge & Fabric] (by Fuzs)](https://www.curseforge.com/minecraft/mc-mods/easy-anvils)
    [Default Dark Mode (by nebuIr)](https://www.curseforge.com/minecraft/texture-packs/default-dark-mode)
    [MiniHUD (by masady)](https://www.curseforge.com/minecraft/mc-mods/minihud)
    [Structory (by botanydev)](https://www.curseforge.com/minecraft/mc-mods/structory)
    [Farmer's Knives [Fabric] (by ianm1647)](https://www.curseforge.com/minecraft/mc-mods/farmers-knives)
    [Resourceful Lib (by ThatGravyBoat)](https://www.curseforge.com/minecraft/mc-mods/resourceful-lib)
    [WorldEdit (by sk89q)](https://www.curseforge.com/minecraft/mc-mods/worldedit)
    [Revelationary (by DaFuqsy)](https://www.curseforge.com/minecraft/mc-mods/revelationary)
    [Patchouli (Fabric/Quilt) (by williewillus)](https://www.curseforge.com/minecraft/mc-mods/patchouli-fabric)
    [MidnightControls (by Motschen)](https://www.curseforge.com/minecraft/mc-mods/midnightcontrols)
    [Visual Workbench [Forge & Fabric] (by Fuzs)](https://www.curseforge.com/minecraft/mc-mods/visual-workbench)
    [Joy of Painting (by xerca0)](https://www.curseforge.com/minecraft/mc-mods/joy-of-painting)
    [Handcrafted (by kekie6)](https://www.curseforge.com/minecraft/mc-mods/handcrafted)
    [Builtin Servers (by D4rkness_King)](https://www.curseforge.com/minecraft/mc-mods/builtin-servers)
    [Comforts (Fabric 1.16.5 - 1.19.2) (by TheIllusiveC4)](https://www.curseforge.com/minecraft/mc-mods/comforts-fabric)
    [Geode+ [Forge/Fabric] (by YeoXuHang)](https://www.curseforge.com/minecraft/mc-mods/geode-plus)
    [ChoiceTheorem's Overhauled Village (by ChoiceTheorem)](https://www.curseforge.com/minecraft/mc-mods/choicetheorems-overhauled-village)
    [Forge Config API Port [Fabric] (by Fuzs)](https://www.curseforge.com/minecraft/mc-mods/forge-config-api-port-fabric)
    [Traveler's Backpack [Fabric] (by Tiviacz1337)](https://www.curseforge.com/minecraft/mc-mods/travelers-backpack-fabric)
    [Rhino (by LatvianModder)](https://www.curseforge.com/minecraft/mc-mods/rhino)
    [Mouse Tweaks (by YaLTeR)](https://www.curseforge.com/minecraft/mc-mods/mouse-tweaks)
    [ShulkerBoxTooltip [Fabric/Forge] (by MisterPeModder)](https://www.curseforge.com/minecraft/mc-mods/shulkerboxtooltip)
    [YUNG's Better Desert Temples (Fabric) (by YUNGNICKYOUNG)](https://www.curseforge.com/minecraft/mc-mods/yungs-better-desert-temples-fabric)
    [oωo (owo-lib) (by gliscowo)](https://www.curseforge.com/minecraft/mc-mods/owo-lib)
    [Architectury API (Fabric/Forge) (by shedaniel)](https://www.curseforge.com/minecraft/mc-mods/architectury-api)
    [Fabric API (by modmuss50)](https://www.curseforge.com/minecraft/mc-mods/fabric-api)
    [Lithium (Fabric) (by jellysquid3_)](https://www.curseforge.com/minecraft/mc-mods/lithium)
    [Easy Magic [Forge & Fabric] (by Fuzs)](https://www.curseforge.com/minecraft/mc-mods/easy-magic)
    [Farmer's Delight [Fabric] (by NewHoryzon)](https://www.curseforge.com/minecraft/mc-mods/farmers-delight-fabric)
    [KubeJS Create (by LatvianModder)](https://www.curseforge.com/minecraft/mc-mods/kubejs-create)
    [Sound Physics Remastered (by henkelmax)](https://www.curseforge.com/minecraft/mc-mods/sound-physics-remastered)
    [Just Enough Items (JEI) (by mezz)](https://www.curseforge.com/minecraft/mc-mods/jei)
    [Cardinal Components (by UpcraftLP)](https://www.curseforge.com/minecraft/mc-mods/cardinal-components)
    [Nether's Delight (Fabric) (by StevePlayzz_)](https://www.curseforge.com/minecraft/mc-mods/nethers-delight-fabric)
    [You're in Grave Danger (by b1n_ry)](https://www.curseforge.com/minecraft/mc-mods/youre-in-grave-danger)
    [Immersive Weathering [FABRIC] (by OrdanaryMods)](https://www.curseforge.com/minecraft/mc-mods/immersive-weathering-fabric)
    [Alloy Forgery (by gliscowo)](https://www.curseforge.com/minecraft/mc-mods/alloy-forgery)
    [YUNG's API (Fabric) (by YUNGNICKYOUNG)](https://www.curseforge.com/minecraft/mc-mods/yungs-api-fabric)
    [Xaero's Minimap (by xaero96)](https://www.curseforge.com/minecraft/mc-mods/xaeros-minimap)
    [Supplementaries (by MehVahdJukaar)](https://www.curseforge.com/minecraft/mc-mods/supplementaries)
    [Beenfo (by Giselbaer)](https://www.curseforge.com/minecraft/mc-mods/beenfo)
    [Spectrum (by DaFuqsy)](https://www.curseforge.com/minecraft/mc-mods/spectrum)
    [YUNG's Better Mineshafts (Fabric) (by YUNGNICKYOUNG)](https://www.curseforge.com/minecraft/mc-mods/yungs-better-mineshafts-fabric)
    [Trinkets (Fabric) (by EmilyPloszaj)](https://www.curseforge.com/minecraft/mc-mods/trinkets)
    [Iris & Oculus Flywheel Compat (by leon_mout)](https://www.curseforge.com/minecraft/mc-mods/iris-flywheel-compat)
    [Cloth Config API (Fabric/Forge) (by shedaniel)](https://www.curseforge.com/minecraft/mc-mods/cloth-config)
    [Bedspreads (Fabric) (by TheIllusiveC4)](https://www.curseforge.com/minecraft/mc-mods/bedspreads-fabric)
    [KubeJS (by LatvianModder)](https://www.curseforge.com/minecraft/mc-mods/kubejs)
    [YUNG's Better Ocean Monuments (Fabric) (by YUNGNICKYOUNG)](https://www.curseforge.com/minecraft/mc-mods/yungs-better-ocean-monuments-fabric)
    [Xaero's World Map (by xaero96)](https://www.curseforge.com/minecraft/mc-mods/xaeros-world-map)
    [WorldEdit Items (by esplat47)](https://www.curseforge.com/minecraft/mc-mods/worldedit-items)
    [playerAnimator (by KosmX)](https://www.curseforge.com/minecraft/mc-mods/playeranimator)
    [Chipped (by terrariumearth)](https://www.curseforge.com/minecraft/mc-mods/chipped)
    [Automobility (by FoundationGames)](https://www.curseforge.com/minecraft/mc-mods/automobility)
    [Decorative Blocks (by stohun)](https://www.curseforge.com/minecraft/mc-mods/decorative-blocks)
    [Good Ending (by orcinus73)](https://www.curseforge.com/minecraft/mc-mods/good-ending)
    [Create Fabric (by tropheusj)](https://www.curseforge.com/minecraft/mc-mods/create-fabric)
    [Indium (by comp500)](https://www.curseforge.com/minecraft/mc-mods/indium)
    [Panorama (by SWDTeam)](https://www.curseforge.com/minecraft/mc-mods/panorama)

**Logs:**
I doubt you need a log for this

**To Reproduce:**
Steps to reproduce the behavior. Format it as a numbered list of steps.

1. Get a silk touch pickaxe
2. Mine mossy stone

**Expected behavior:**
Mossy stone should drop mossy stone when mined with silk touch

**Comment by AstralOrdana** [comment]
fixed for next version

**Comment by ambientNexus** [comment]
Issue reappeared in current version
