### ISSUE TITLE
Generators cannot be disabled, specifically basalt generator

### ISSUE THREAD

**Issue by brianfreud** [AstralOrdana/Immersive-Weathering#272]
**Describe the bug:**
The various generators have string support in the different language files, seen in https://github.com/AstralOrdana/Immersive-Weathering/tree/17e4d29785ec23aa76c7a136378dfb983e219c70/common/src/main/resources/assets/immersive_weathering/lang 

However, the different language files are inconsistant between them as to the config key and description text's key:
en_es: text.autoconfig.immersive_weathering.option.worldgenConfig.icicleFeature
en_us: config.immersive_weathering.generation.icicle_feature.descriptionKey and config.immersive_weathering.generation.icicle_feature

The basalt generator  https://github.com/AstralOrdana/Immersive-Weathering/blob/28aa0b01eb6ee5f11012127e377242bc1cc97c7f/common/src/main/resources/data/immersive_weathering/fluid_generators/basalt.json#L6  only appears in the en_es file, as text.autoconfig.immersive_weathering.option.generatorsConfig.basaltGenerator.  None of the other language files have this key or a description text.

Additionally, none of the generators are listed in either immersive_weathering-common.toml or immersive_weathering-client.toml as configurable options.

The basalt generator is problematic when I'm drilling a perimeter with a gantry using the create mod.  If I cut through a patch of basalt, and there's even a single lava source, the lava source should be left exposed so a sweeper can come through and get rid of it.  However, this generator makes it such that the flat surface that was just cut doesn't stay flat.  Instead, having that single lava source above that basalt causes more basalt to spring up around the edges of the lava.  (See photo below.)

**Comment by brianfreud** [comment]
![Screenshot from 2023-05-11 08-02-38](https://github.com/AstralOrdana/Immersive-Weathering/assets/49247/073d40bc-565a-4a96-936b-f50058cd68b3)

**Comment by AstralOrdana** [comment]
all generators can be modified or disabled via datapack
