### ISSUE TITLE
Some custom generators are not working

### ISSUE THREAD

**Issue by loong218-toast** [AstralOrdana/Immersive-Weathering#274]
**Bug:**
1. Crying obsidian is not generated but instead an ordinary obsidian is generated. (2023/22/06 update: crying obsidian can be generated if the soul fire is at the side but not front unlike the picture given in the wiki. It does not consume lava source block)
2. The calcite generator generates a blackstone instead of calcite even if the bone block is placed vertically. Flowing lava or non-flowing lava produces the same result. 
3. Smooth basalt is not generated.

Other generators work fine.

**Versions:**
Minecraft version: 1.18.2
Immersive Weathering version: 2.5.6
Fabric API version: 0.58.0

I am using the latest Valhesia Enhanced Vanilla minecraft modpack. Everything is tested in creative mode.

**Other mods:**
All mods included in Valhesia Enhanced Vanilla.

[latest.log](https://github.com/AstralOrdana/Immersive-Weathering/files/11664764/latest.log)

**To Reproduce:**
I just follow the [wiki](https://github.com/AstralOrdana/Immersive-Weathering/wiki/Custom-Generators) and use the modpack I mentioned earlier.

**Screenshots:**
![2023-06-06_20 37 31](https://github.com/AstralOrdana/Immersive-Weathering/assets/77558802/366e38f9-498d-4788-8bf8-e4c99b30630a)
![2023-06-06_20 37 45](https://github.com/AstralOrdana/Immersive-Weathering/assets/77558802/894fbe5c-60f0-4334-951e-fa3c715893ec)
![2023-06-06_20 38 28](https://github.com/AstralOrdana/Immersive-Weathering/assets/77558802/ef32ec87-1a1c-4a72-adde-2dc55be05f96)

**Additional info:**
Please fix

**Comment by AstralOrdana** [comment]
issue cannot be replicated in the latest release
