### ISSUE TITLE
Configurable wheat drops from weeds

### ISSUE THREAD

**Issue by ranenvious** [AstralOrdana/Immersive-Weathering#278]
**Feature:**

I think that a config option for whether or not (or how much) wheat is dropped/given from weeds should be added

**Alternatives:**

There are no real alternatives I can think of here. One alternative might be adding a config option to change how fast weeds grow (as in, how long it takes them to go from 0% growth to 100% grown and harvestable) but that seems like a different feature entirely. 

**Additional info:**

My reason for suggesting this is that, in combination with mods like create that allow crop auto-harvesting, weeds pose very little downside. Since weeds give wheat, (and a fair amount of wheat at that) even if your entire field is entirely replaced with weeds, there is really no reason to change it back to actual wheat. 

Weed-farming as an alternative to actual wheat is an interesting concept, so I don't think weeds just flat out shouldn't drop wheat at all, but letting it be configured would let it be more effectively balanced against normal wheat.

**Comment by mintynoura** [comment]
Weeds drop wheat? don't they drop dandelions?

**Comment by ranenvious** [comment]
> Weeds drop wheat? don't they drop dandelions?

are they not supposed to drop wheat? They do in my modpack and I never manually changed it. I guess it's possible a conflict is causing an issue but that seems like an extremely weird conflict.

**Comment by AstralOrdana** [comment]
known issue where weeds drop wheat instead of dandelions, fixed for next update

**Comment by dandalous** [comment]
This issue occurs with the latest version (2.0.3) on Forge 1.20.1
