### ISSUE TITLE
Crash at worldgen/entering world (forge)

### ISSUE THREAD

**Issue by agentwolf88** [AstralOrdana/Immersive-Weathering#28]
[crash-2022-03-21_12.20.53-server.txt](https://github.com/AstralOrdana/Immersive-Weathering/files/8315031/crash-2022-03-21_12.20.53-server.txt)

**Comment by AstralOrdana** [comment]
Possible incompat related to the fluid mixin, possibly not an issue related to us since the log talks about pneumaticraft oil and red sand.

**Comment by desht** [comment]
The problem here is your direct reference to the `fluid` field in your `WaterMixin#shouldSpreadFluid()` method.  The Forge `getFluid()` method must be used here since the fluid is only available through the Forge-added supplier for modded fluids.

**Comment by MehVahdJukaar** [comment]
fixed
