### ISSUE TITLE
Collision issue with cryosol block (Snow! Real Magic!) 

### ISSUE THREAD

**Issue by AlonsoCid** [AstralOrdana/Immersive-Weathering#282]
**Describe the bug:**
When snow (with the Snow! Real Magic! mod installed) is placed on a cryosol block, it is placed inside the block as if it wasn’t there. I have tested it and it happened even with only those 2 mods installed. I don’t know if the problem is in your mod or in the other, but I would appreciate it if you could take a look and fix it.

EDIT: Actually it happends with any block of your mod.

**Versions: (BEFORE SUBMITTING A BUG REPORT, make sure you have the most up-to-date versions of Immersive Weathering, Moonlight Lib and Supplementaries)**
Minecraft version: 1.19.2
Immersive Weathering version: 1.2.9
Moonlight Lib version: 2.2.40
Fabric API / QSL / Forge version: Fabric API 0.76.0

**Other mods:**
Sodium
Indium
Kiwi
Snow! Real Magic! ⛄ (Fabric)

**Logs:**
Last log: <script src="https://gist.github.com/AlonsoCid/ef11a74cd341f3f535717436084532f0.js"></script>
Launcher log: <script src="https://gist.github.com/AlonsoCid/c0e4cf86f140efdc4df6dacbc034d89b.js"></script>

**To Reproduce:**
1. Install Immersive weathering and Snow! Real Magic!
2. Go to a snow biome and find a cryosol block
3. Place a snow sheet over it

**Expected behavior:**
The snow will fall through the block, making a snow layer inside.

**Screenshots:**
![image](https://github.com/AstralOrdana/Immersive-Weathering/assets/137985259/73d07eb5-e738-4029-9d58-86d34c5ba4c7)

**Additional info:**
Snow! Real Magic! web: https://www.curseforge.com/minecraft/mc-mods/snow-real-magic-fabric

**Comment by AlonsoCid** [comment]
I have submit the issue to the other mod author here is the discussion in case it can help you: https://github.com/Snownee/SnowRealMagic/issues/281

**Comment by Drakkoo3344** [comment]
> I have submit the issue to the other mod author here is the discussion in case it can help you: [Snownee/SnowRealMagic#281](https://github.com/Snownee/SnowRealMagic/issues/281)

yeah but the immersive snow mod doesnt cause the glitch, its completely on immersive weathering end

**Comment by thedeerirty** [comment]
Giving this a bump - hoping for a solution.

**Comment by AstralOrdana** [comment]
fixed for next version
