### ISSUE TITLE
Rooted Dirt growing Hanging Roots does not check if there's space, allowing you to break all blocks including Bedrock

### ISSUE THREAD

**Issue by aaronhowser1** [AstralOrdana/Immersive-Weathering#288]
**Describe the bug:**
A clear and concise description of what the bug is. Include as much information as you can. Images are often helpful, especially screenshots of the F3 debug menu.

**Versions: (BEFORE SUBMITTING A BUG REPORT, make sure you have the most up-to-date versions of Immersive Weathering, Moonlight Lib and Supplementaries)**
Minecraft version: 1.19.2
Immersive Weathering version: immersive_weathering-1.19.2-1.2.9-forge
Moonlight Lib version: moonlight-1.19.2-2.2.43-forge
Fabric API / QSL / Forge version: 43.2.14

**To Reproduce:**
Steps to reproduce the behavior. Format it as a numbered list of steps.

1. Place Rooted Dirt above Bedrock
2. Allow it to grow with time or force it with Bone Meal
3. Observe how the Bedrock is gone

**Expected behavior:**
It should simply fail if there's a block below

**Screenshots:**
If applicable, add screenshots to help explain your problem. https://screenshot.help/
![image](https://github.com/AstralOrdana/Immersive-Weathering/assets/15698722/50f6d66e-0e5e-481e-8cc9-93b7dff41463)
![image](https://github.com/AstralOrdana/Immersive-Weathering/assets/15698722/600506bd-d00a-4388-9e4e-8b05ea87c8b7)

**Comment by AstralOrdana** [comment]
fixed for next version
