### ISSUE TITLE
Snowy cobblestone blocks should have inversed texture

### ISSUE THREAD

**Issue by ThinkWithPbody** [AstralOrdana/Immersive-Weathering#289]
![image](https://github.com/AstralOrdana/Immersive-Weathering/assets/51525460/bf2c85d8-0b25-48c4-b78e-5f6fdfe78a64)

I love all the new blocks added by immersive weathering, but for the snowy cobblestone blocks they are not entirely covered in snow, so it makes sense that there should only be snow in the crevices as opposed to having snow where it sticks out.

**Comment by AstralOrdana** [comment]
suggestion not a bug, also its meant to imply the snow is resting on top of horizontal cobbles

**Comment by ThinkWithPbody** [comment]
Thanks for taking a look at this. While I appreciate your opinion I don't recall the last time I see snow behaving like this in real life and for me, it breaks the immersion a little... Wind and footsteps make it so that if there's not enough snow to cover everything, it's always in the crevices. If you do end up changing some textures in the future please reconsider this part. Thank you very much.
