### ISSUE TITLE
The creative tab name isn't localized

### ISSUE THREAD

**Issue by aaronhowser1** [AstralOrdana/Immersive-Weathering#290]
**Describe the bug:**

![image](https://github.com/AstralOrdana/Immersive-Weathering/assets/15698722/3bb209fa-50c3-425f-a57f-f35f01d876eb)

Immersive Weathering version:

immersive_weathering-1.19.2-1.2.9-forge

**Comment by AstralOrdana** [comment]
resolved for next update
