### ISSUE TITLE
[Suggestion] Concrete spalling and weathered terracotta

### ISSUE THREAD

**Issue by Eronparks** [AstralOrdana/Immersive-Weathering#291]
**Feature:**

Concrete will start chipping and spalling over time due to moisture and air. For terracotta it would start to de-color and form stains on  it and cracks and emit dust.

**Additional info:**

A possible concept for repairing concrete before it becomes too damaged could maybe be with powder? To sand off the spalled parts to restore it to it's pristine look or maybe have a slightly different tone to give it a patchy look.
A brush and sponge could be used to clean terracotta, and like concrete. You will need clay to restore the cracks.

![831c40c6bb8d8b03fd01711269b28a4c](https://github.com/AstralOrdana/Immersive-Weathering/assets/92606191/dd7d32aa-7be0-4923-869b-056c3b19d1e2)
![concrete-spalling copy](https://github.com/AstralOrdana/Immersive-Weathering/assets/92606191/b5384837-a619-4982-8f9a-b736a73c998a)

**Comment by AstralOrdana** [comment]
suggestion noted but not planned at this time as 
1. concrete and terracotta have so many color variations that any new blocks related to them are a significant undertaking and 
2. People often build with them in mass amounts to make use of their flat colors so making them weather would be less than ideal
