### ISSUE TITLE
Desire Paths can be formed under blocks, breaking them

### ISSUE THREAD

**Issue by aaronhowser1** [AstralOrdana/Immersive-Weathering#293]
**Describe the bug:**

When walking over grass/dirt repeatedly, it can turn into a path. Very nice, very cool, I actually really do love it.

But, it doesn't check if that grass/dirt is supporting something. That means stuff like Doors break, and more importantly things like Botania's magical flowers.

**Versions: (BEFORE SUBMITTING A BUG REPORT, make sure you have the most up-to-date versions of Immersive Weathering, Moonlight Lib and Supplementaries)**
Minecraft version: 1.19.2
Immersive Weathering version: immersive_weathering-1.19.2-1.2.9-forge
Moonlight Lib version: moonlight-1.19.2-2.2.43-forge
Fabric API / QSL / Forge version: Forge 43.2.21

**Expected behavior:**

It should only turn into a path if it's safe to do so

**Comment by AstralOrdana** [comment]
iw's desire paths are experimental and unfortuntely not fully supported at this time. They may be reworked in a future version or fully removed but I cannot guarantee anything rn. To avoid mod conflicts, disabling them entirely via config is your best option.
