### ISSUE TITLE
World Loading Issue when using I.W. and Dynamic Trees: Terralith

### ISSUE THREAD

**Issue by OxiiGiin1** [AstralOrdana/Immersive-Weathering#299]
**Describe the bug:**
World Loading either stops at any percentage, or you get into the game and eventually, the world eventually stops and you have to force close the client.

**Versions: (BEFORE SUBMITTING A BUG REPORT, make sure you have the most up-to-date versions of Immersive Weathering, Moonlight Lib and Supplementaries)**
Minecraft version: 1.19.2 
Immersive Weathering version: 1.19.2-1.2.10 Forge
Moonlight Lib version: 1.19.2-2.2.44 Forge
Fabric API / QSL / Forge version: Forge 43.2.21

**Other mods:**
Mods listed in Logs

**Logs:**
[latest.log](https://github.com/AstralOrdana/Immersive-Weathering/files/12386856/latest.log)

**To Reproduce:**
Steps to reproduce the behavior. Format it as a numbered list of steps.

1. Open Game
2. Create World
3. Wait for world loading to pause or get into the game and wait for it to pause.

**Expected behavior:**
Expect the game to run smoothly

**Screenshots:**

**Additional info:**
Talked to MaxHyper from Dynamic Trees and he said to get into contact with you guys.

**Comment by AstralOrdana** [comment]
There is no reason to assume iw has anything to do with this, closed unless cause is shown. Looking at the log it just seems like you have an incredibly large number of mods.
