### ISSUE TITLE
1.20 Port

### ISSUE THREAD

**Issue by Rebel459** [AstralOrdana/Immersive-Weathering#300]
Is this mod going to see an update to 1.20 (Fabric version)? It's a great mod and it would be awesome to be able to use it in 1.20

Thanks

**Comment by Rebel459** [comment]
Never mind, I see it's already being worked on in a different branch, my bad

**Comment by SafeOfArsenal** [comment]
![image](https://github.com/AstralOrdana/Immersive-Weathering/assets/66153781/8dc7cfcb-f8eb-4e3a-9c78-25100300b4f1)

**Comment by AstralOrdana** [comment]
you wanna port it yourself?
