### ISSUE TITLE
Stems aren't dropping any scales on stripping

### ISSUE THREAD

**Issue by zeresss** [AstralOrdana/Immersive-Weathering#301]
1. Find any stem
2. Try to strip them using an axe and right click
3. They won't drop any scales
They should drop crimson or warped scales based on stem type

Video: https://drive.google.com/file/d/1mhKhIGeNNRHt0HVwrgZJqCRo-AhrRtJY/view?usp=sharing

Minecraft version: 1.19.2
Immersive Weathering version: 1.2.10 
Moonlight Lib version: 2.2.44
Fabric API version: 0.76.1

**Comment by mintynoura** [comment]
Can confirm in Forge 43.2.3 as well

**Comment by zeresss** [comment]
I am no longer experiencing this bug so I think this issue can be closed.
