### ISSUE TITLE
1.19.2-1.2.10 Breaks Create Mod 1.19.2-1.2.9 works fine

### ISSUE THREAD

**Issue by ebaystudio** [AstralOrdana/Immersive-Weathering#303]
1.2.9 is the last version to work with 0.5.1 of the Create Fabric Mod. 

```
The game crashed whilst initializing game
Error: java.lang.RuntimeException: Could not execute entrypoint stage 'main' due to errors, provided by 'create'!
```
[crash-2023-09-12_22.54.41-client.txt](https://github.com/AstralOrdana/Immersive-Weathering/files/12592975/crash-2023-09-12_22.54.41-client.txt)

**Comment by CactusDuud** [comment]
Not the dev, but it seems like there are multiple issues occurring here. Immersive Weathering (1.19.2-1.2.10) works fine with Create Fabric (0.5.1-c-build.1160+mc1.19.2) on my device. Try testing with other mods in the crash log (my guess would be Terrestria).
