### ISSUE TITLE
Make mulch same height as farmlands

### ISSUE THREAD

**Issue by Desoroxxx** [AstralOrdana/Immersive-Weathering#308]
Sorry for not using the template, this is simple enough that it doesn't need it.

This mod is awesome, but there is one little thing that pains me with it, mulch height, since it is a full height block, it doesn't line up with paths like farmlands do this is very minor, but the second point isn't.
Here is my second point, being a full height block, snow can spawn on it and become annoying.

**Comment by AstralOrdana** [comment]
working as intended
