### ISSUE TITLE
1.20 forge crash

### ISSUE THREAD

**Issue by vivagabe** [AstralOrdana/Immersive-Weathering#314]
**Describe the bug:**
Game fails to load

**Versions: (BEFORE SUBMITTING A BUG REPORT, make sure you have the most up-to-date versions of Immersive Weathering, Moonlight Lib and Supplementaries)** I have the latest versions of these
Minecraft version: 1.20.1
Immersive Weathering version: Beta
Moonlight Lib version: 2.8.77
Fabric API / QSL / Forge version:47.2.0

**Other mods:**
attatched

**Logs:**
*Even if the game does not crash they may be useful!*
Please provide the following logs:
From .minecraft/logs :  "latest.log" as well as "debug.log" if it exists. From .minecraft : "launcher_log" as well as a
file that starts with "hs_err" if it exists. Note: Double check that the logs are from the correct time. ex, don't give
us a log from a month ago because you forgot to check the date.

**To Reproduce:**
Start minecraft

**Expected behavior:**
minecraft to load up.

**Screenshots:**
[latest.log](https://github.com/AstralOrdana/Immersive-Weathering/files/13792242/latest.log)

N/A

**Additional info:**
I think it may have something to do with Quark, which is in beta form at the moment. Also, i am using sinytra connector. Thank you!
[latest.log](https://github.com/AstralOrdana/Immersive-Weathering/files/13792254/latest.log)

**Comment by SiverDX** [comment]
Regions Unexplored does their mixin in an incompatible way

https://github.com/UHQ-GAMES-MODS/REGIONS_UNEXPLORED_FORGE/blob/9b08723d1f6bf818ad6ae8185656e8a009e4d01f/src/main/java/net/regions_unexplored/mixin/EatBlockGoalMixin.java#L53-L71

You will need to ask them to move away from things like `Override` and `Redirect` since those should be avoided at all cost

There is nothing Immersive Weathering can do here

**Comment by KirboSoftware** [comment]
My apologies (a Regions unexplored dev here). I made that mixin as more as a hacky way. Will look into fixing this 👍

**Comment by KirboSoftware** [comment]
also, this seems to be a priority issue which either us of could resolve. 

> Mixin apply failed immersive_weathering-common.mixins.json:EatBlockGoalMixin -> net.minecraft.world.entity.ai.goal.EatBlockGoal: org.spongepowered.asm.mixin.injection.throwables.InvalidInjectionException @At("INVOKE") on net/minecraft/world/entity/ai/goal/EatBlockGoal::canEatRootedGrass with priority 1000 cannot inject into net/minecraft/world/entity/ai/goal/EatBlockGoal::m_8036_()Z merged by net.regions_unexplored.mixin.EatBlockGoalMixin with priority 1000 [PREINJECT Applicator Phase -> immersive_weathering-common.mixins.json:EatBlockGoalMixin -> Prepare Injections ->  -> wrapOperation$zck000$canEatRootedGrass(Lnet/minecraft/world/level/block/state/BlockState;Lnet/minecraft/world/level/block/Block;Lcom/llamalad7/mixinextras/injector/wrapoperation/Operation;)Z -> Prepare]
org.spongepowered.asm.mixin.injection.throwables.InvalidInjectionException: @At("INVOKE") on net/minecraft/world/entity/ai/goal/EatBlockGoal::canEatRootedGrass with priority 1000 cannot inject into net/minecraft/world/entity/ai/goal/EatBlockGoal::m_8036_()Z merged by net.regions_unexplored.mixin.EatBlockGoalMixin with priority 1000 [PREINJECT Applicator Phase -> immersive_weathering-common.mixins.json:EatBlockGoalMixin -> Prepare Injections ->

easiest solution would be adjusting the priority of said mixin's.

**Comment by KirboSoftware** [comment]
This issue should be resolved in the following regions unexplored version: 0.5.3.1 👍 I've completely revamped the mixin in question, so if there are any issues related to this. Please tag me 👍
