### ISSUE TITLE
Crash related with particles on leaf pile block

### ISSUE THREAD

**Issue by e2e13** [AstralOrdana/Immersive-Weathering#316]
**Alpha versions:**
If you are using an alpha version (like current 1.20.1 one) be aware that we are aware of the more obvious issues and are working on them. Not to overwhelm the team only report things that is not obvious

**Describe the bug:**
A clear and concise description of what the bug is. Include as much information as you can. Images are often helpful, especially screenshots of the F3 debug menu.

Minecraft version:1.20.1
Immersive Weathering version:1.3.2
Moonlight Lib version:2.8.78
Forge version:47.2.0

**Other mods:**
[mod list](https://pastebin.com/nVA78BVt)

**Logs:**
*Even if the game does not crash they may be useful!*

[latest.log](https://github.com/AstralOrdana/Immersive-Weathering/files/13802472/latest.log)

**To Reproduce:**
Steps to reproduce the behavior. Format it as a numbered list of steps.

1.find a leaf pile
2.run over it or jump from a height that creates particles
3. the game crashes

**Expected behavior:**
Game not to crash

**Additional info:**
might be incompatibility with some other mods but did not test it enough. being the main suspect blue skies mod, nvm blue skies has nothing to do

**Comment by Powermonkey00** [comment]
I just wanted to +1 this, having a similar problem.  Disabling Immersive Weathering prevents the crash from occuring.  Here's what looked relevant in my log:

java.lang.NullPointerException: Cannot invoke "net.minecraft.core.particles.ParticleOptions.m_6012_()" because "p_104706_" is null
	at net.minecraft.client.multiplayer.ClientLevel.m_7106_(ClientLevel.java:590) ~[client-1.20.1-20230612.114412-srg.jar%23672!/:?] {re:mixin,pl:runtimedistcleaner:A,re:classloading,pl:rei_plugin_compatibilities:B,pl:mixin:APP:citadel.mixins.json:client.ClientLevelMixin,pl:mixin:APP:supplementaries-common.mixins.json:ClientLevelMixin,pl:mixin:APP:mixins.oculus.vertexformat.json:block_rendering.MixinClientLevel,pl:mixin:APP:flywheel.mixins.json:ClientLevelMixin,pl:mixin:APP:naturalist-common.mixins.json:ClientLevelMixin,pl:mixin:APP:architectury.mixins.json:MixinClientLevel,pl:mixin:APP:sound_physics_remastered.mixins.json:ClientLevelMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at com.ordana.immersive_weathering.blocks.LeafPileBlock.m_7892_(LeafPileBlock.java:152) ~[immersive_weathering-1.20.2-1.3.2-forge.jar%23527!/:?] {re:classloading,pl:rei_plugin_compatibilities:B}

**Comment by misfit-stag** [comment]
+1 this as well. Same error as Powermonkey.

Minecraft version: 1.20.1
Immersive Weathering version: 1.3.2
Moonlight Lib version: 2.8.79
Forge version: 47.2.19

**Comment by Kirisoup** [comment]
Happens in fabric 1.20.1, modlist: 
- fabric-api-0.91.0+1.20.1
- modmenu-7.2.2
- moonlight-1.20-2.8.78-fabric
- immersive_weathering-1.20.2-1.3.2-fabric

Should not be a compatibility issue.

`	at com.ordana.immersive_weathering.blocks.LeafPileBlock.method_9548(LeafPileBlock.java:152)`

Edit: Seems to be fixed in the newest commit!

**Comment by Kirisoup** [comment]
Sorry that I don't really know much about java and mc modding, but it seems like that at `Immersive-Weathering/common/src/main/java/com/ordana/immersive_weathering/blocks/LeafPileBlock.java:153`, `p.get()` in `level.addParticle(p.get(),` seems to be null? 

By running the `level.addParticle` thingy inside `if (p.get() != null) {}`, particles are not created and game didn't crash.

**Comment by AstralOrdana** [comment]
fixed
