### ISSUE TITLE
Crash when placing vanilla hanging roots as well as clicking the top of blocks

### ISSUE THREAD

**Issue by Gamershy** [AstralOrdana/Immersive-Weathering#318]
**Describe the bug:**
A clear and concise description of what the bug is. Include as much information as you can. Images are often helpful, especially screenshots of the F3 debug menu.

**Versions: (BEFORE SUBMITTING A BUG REPORT, make sure you have the most up-to-date versions of Immersive Weathering, Moonlight Lib and Supplementaries)**
Minecraft version: 1.19.2
Immersive Weathering version: 1.2.10
Moonlight Lib version: 2.3.6
Fabric API / QSL / Forge version: 43.2.21

**Other mods:**
None

**Logs:**
The game crashed whilst unexpected error
Error: java.lang.IllegalArgumentException: Cannot set property DirectionProperty{name=facing, clazz=class net.minecraft.core.Direction, values=[north, south, west, east]} to up on Block{immersive_weathering:hanging_roots_wall}, it is not an allowed value - From the launcher itself

**To Reproduce:**
1. Literally place hanging roots anywhere but the side of a block

**Expected behavior:**
The vanilla hanging roots to be placed, or no roots at all in the case of placing on top.

**Screenshots:**
N/A

**Additional info:**
This is a fairly fatal issue, as it locks player out of using hanging roots, and can result in accidental crashes in the event of clicking the top of a block. It seems you may have overridden the entire item instead of just adding a case for when the item is placed on the side of a block, as the crash refers only to the "immersiveweathering:hanging_root_wall" block ID as opposed to anything vanilla.
With how fatal of an issue this is, I'd ask that this be fixed as soon as possible, as it could lead to some fairly severe issues.

**Comment by AstralOrdana** [comment]
fixed for 2.0.0, 
further 1.19 support is not planned at this time
