### ISSUE TITLE
Player throws regular bricks even if they're throwing a different type

### ISSUE THREAD

**Issue by ChillyBeanBAM** [AstralOrdana/Immersive-Weathering#319]
**Describe the bug:**
When Supplementaries is installed while throwing any type of brick item except the regular one, the player will sometimes throw regular bricks alongside the one in their hand.

**Versions: (BEFORE SUBMITTING A BUG REPORT, make sure you have the most up-to-date versions of Immersive Weathering, Moonlight Lib and Supplementaries)**
Minecraft version: 1.20.1
Immersive Weathering version: 2.0.0
Moonlight Lib version: 2.9.6
Supplementaries version: 2.7.31
Fabric API / QSL / Forge version: 0.91.0

**Other mods:**
List all mods that you're using; could be in the form of a list of the filenames, a crash report list, a screenshot of
the mods folder, etc. Just make sure all mods used are known!

- Cloth Config (v11.1.118)
- Dynamic FPS (v3.3.3)
- Memory Leak Fix (v1.1.5)
- Model Gap Fix (v1.14)
- Mod Menu (v7.2.2)
- The Open Sauce Toast Killer (v1.0)
- Spelunkery (v0.3.5)
- Supplementaries Squared (v1.1.12)
- Yeetus Experimentus (v2.3.0 beta)

**Logs:**
*Even if the game does not crash they may be useful!*
Please provide the following logs:
From .minecraft/logs :  "latest.log" as well as "debug.log" if it exists. From .minecraft : "launcher_log" as well as a
file that starts with "hs_err" if it exists. Note: Double check that the logs are from the correct time. ex, don't give
us a log from a month ago because you forgot to check the date.
[launcher_log.txt](https://github.com/AstralOrdana/Immersive-Weathering/files/14088907/launcher_log.txt)
[latest.log](https://github.com/AstralOrdana/Immersive-Weathering/files/14088908/latest.log)

**To Reproduce:**
Steps to reproduce the behavior. Format it as a numbered list of steps.

1. Have any brick item in your inventory except the regular one
2. Repeatedly throw the brick in your hand

**Expected behavior:**
No regular bricks are thrown at all.

**Screenshots:**
![2024-01-29_14 34 21](https://github.com/AstralOrdana/Immersive-Weathering/assets/109490279/05f7b3a2-4ca7-45b8-bd99-00ab7e183cdf)

**Additional info:**
I dunno if this has anything to do with Supplementaries only, but I felt like it was worth noting here.

**Comment by AstralOrdana** [comment]
report this supplementaries
