### ISSUE TITLE
Snowball drop spam

### ISSUE THREAD

**Issue by nimbXnumb** [AstralOrdana/Immersive-Weathering#321]
**Describe the bug:**
Snowballs drop from snowy block when melted with light source.

**Versions:**
Minecraft version: 1.20.1
Immersive Weathering version: 1.20.1-2.0.0
Moonlight Lib version: fabric_1.20-2.9.7
Fabric API / QSL / Forge version: 0.91.0+1.20.1

**Other mods:**
Sodium

**Logs:**
Not needed

**To Reproduce:**

1. Go to a snowy biome and use command /weather rain (or thunder)
2. Build a 3x3 box with stone bricks under clear sky
3. Place lantern inside of the box (top of lantern should be covered)
4. Use command /gamerule randomTickSpeed 300
5. Observe snowballs droping

**Expected behavior:**
No snowballs droping, as vanilla snow does when melting

**Screenshots:**
![2024-02-01_20 16 07](https://github.com/AstralOrdana/Immersive-Weathering/assets/117385950/b0309f7e-a01e-49da-a109-f16389dd6ea5)

**Additional info:**
Not related to this bug, but. Grass is freezing and unfreezing in a loop in snowy biomes. Permafrost is present in taiga biomes (and probably other not so cold ones).

**Comment by AstralOrdana** [comment]
this should be fixed by making it so blocks cannot become snowy if they are exposed to light, note made to fix

**Comment by MehVahdJukaar** [comment]
i disagree here. I dont think they should drop snowballs at all when melting. They should just melt away like snow layers. Leave snowball for player inreraction (as a hand would be needed to collect the (non melted) snow)

**Comment by AstralOrdana** [comment]
fixed for 2.0.1
