### ISSUE TITLE
Game crashed upon something with the leaf piles.

### ISSUE THREAD

**Issue by ghost** [AstralOrdana/Immersive-Weathering#323]
**Describe the bug:**
I'm unsure what going on, but it seems that the leaf piles are causing some kind of crash? I'm unsure if it was from some particles?

Minecraft version: 1.20.1
Immersive Weathering version: 2.0.0
Moonlight Lib version: 2.9.7
Fabric API / QSL / Forge version: 47.2.19

**Other mods:**
  [✔] additional_enchantments-1.20.1-0.3.5-all
  [✔] additionaladditions-6.0.1
  [✔] alternategunpowder-1.0.0-1.20.1
  [✔] autohud-6.3.4+1.20.1-forge
  [✔] backpacked-forge-1.20.1-2.2.5
  [✔] better-trees-1.7
  [✔] CerbonsAPI-Forge-1.20.1-1.1.0
  [✔] CerbonsBetterBeacons-Forge-1.20.1-1.1.1
  [✔] do_a_barrel_roll-forge-3.5.0+1.20.1
  [✔] dynamiccrosshair-7.4.4+1.20-forge
  [✔] EasyAnvils-v8.0.1-1.20.1-Forge
  [✔] EasyMagic-v8.0.1-1.20.1-Forge
  [✔] elytra_physics-forge-2.0
  [✔] ElytraBombing-Forge-1.20.1-1.0.0
  [✔] embeddium-0.2.18+mc1.20.1
  [✔] embeddiumplus-1.20.1-v1.2.3-build
  [✔] EnchantingInfuser-v8.0.2-1.20.1-Forge
  [✔] entity_model_features_forge_1.20.1-1.2.3
  [✔] entity_texture_features_forge_1.20.1-5.2.2
  [✔] framework-forge-1.20.1-0.6.16
  [✔] geckolib-forge-1.20.1-4.4.2
  [✔] jei-1.20.1-forge-15.2.0.27
  [✔] LeavesBeGone-v8.0.0-1.20.1-Forge
  [✔] NonConflictKeys-Forge-1.19.X-1.20-1.0.0
  [✔] oculus-mc1.20.1-1.6.13
  [✔] paddedelytras-1.20-1.0
  [✔] PuzzlesLib-v8.1.14-1.20.1-Forge
  [✔] QuitOrNot-1.0.1+Forge+1.20.1
  [✔] sculkhorde-1.20.1-0.9.0-Beta1
  [✔] squaremap-forge-mc1.20.1-1.2.0
  [✔] textrues_embeddium_options-0.1.3+mc1.20.1
  [✔] UniversalEnchants-v8.0.0-1.20.1-Forge
  [✔] witherstormmod-1.20.1-4.0.1.1

**Logs:**
[ImmersiveCrash.txt](https://github.com/AstralOrdana/Immersive-Weathering/files/14132299/ImmersiveCrash.txt)

**To Reproduce:**
Steps to reproduce the behavior. Format it as a numbered list of steps.
1. Chop down a tree.
2. Have the leaf piles fall on an area with active particles.

**Expected behavior:**
The game crashes.

**Comment by AstralOrdana** [comment]
looks to me like incompat with whatever `leavesbegone` is/does

**Comment by MehVahdJukaar** [comment]
fixed
