### ISSUE TITLE
Iron products sound missing

### ISSUE THREAD

**Issue by 123qwqeq** [AstralOrdana/Immersive-Weathering#324]
mod ：immersive_weathering-1.20.1-2.0.0-fabric.jar
fabric ：0.15.6

**Comment by AstralOrdana** [comment]
not enough information provided

**Comment by dabomb6405** [comment]
I'm pretty sure this issue is referring to Iron Doors and Trapdoors not making any sounds when opened or closed, considering I'm having this same issue
