### ISSUE TITLE
Game crashes upon placing moss clump on cobblestone

### ISSUE THREAD

**Issue by AVerySmellyBoy** [AstralOrdana/Immersive-Weathering#325]
**Describe the bug:**
A clear and concise description of what the bug is. Include as much information as you can. Images are often helpful, especially screenshots of the F3 debug menu.

**Versions: (BEFORE SUBMITTING A BUG REPORT, make sure you have the most up-to-date versions of Immersive Weathering, Moonlight Lib and Supplementaries)**
Minecraft version: 1.20.1
Immersive Weathering version: 1.20-2.0.0
Moonlight Lib version: 1.20-2.9.7
Fabric API / QSL / Forge version: Forge 47.2.0

**Other mods:**
![image](https://github.com/AstralOrdana/Immersive-Weathering/assets/149231016/20081e82-de74-40c3-9c1b-8181a9eda51f)

**Logs:**
[latest.log](https://github.com/AstralOrdana/Immersive-Weathering/files/14136588/latest.log)
[debug.log](https://github.com/AstralOrdana/Immersive-Weathering/files/14136592/debug.log)

**To Reproduce:**
Place Moss Clump on a Cobblestone block

**Expected behavior:**
I was expecting it to put the moss layer on the cobble, yet it crashes instantly.

**Comment by AstralOrdana** [comment]
appears to be caused by the QuarkPluginImpl which i believe is deprecated and should have been removed, will look into

**Comment by MehVahdJukaar** [comment]
fixed
