### ISSUE TITLE
Game crashes when setting fire on mossy stone.

### ISSUE THREAD

**Issue by Epresin** [AstralOrdana/Immersive-Weathering#33]
Minecraft Version:1.18.2
Fabric Version:0.13.3
Mods:
fabric-api-0.48.0+1.18.2
immersive_weathering-2.3.2

Right click the mossy stone with flint and steel,the game crashed.

[crash-2022-03-26_13.55.42-client.txt](https://github.com/AstralOrdana/Immersive-Weathering/files/8354785/crash-2022-03-26_13.55.42-client.txt)

**Comment by AstralOrdana** [comment]
mossy stone's functionality isn't fully implemented, this will be fixed in the next update.

**Comment by AstralOrdana** [comment]
fixed for fabric

**Comment by MehVahdJukaar** [comment]
closing this since it wasnt an issue on forge
