### ISSUE TITLE
Crash when right clicking/extinguishing charred logs on server

### ISSUE THREAD

**Issue by Squ-Cog** [AstralOrdana/Immersive-Weathering#332]
**Describe the bug:**
When playing on a modded server, when right clicking to extinguish a charred log, the server crashes. It does work on singleplayer, and right before crashing the paricles do emit.

**Versions: (BEFORE SUBMITTING A BUG REPORT, make sure you have the most up-to-date versions of Immersive Weathering, Moonlight Lib and Supplementaries)**
Minecraft version: 1.20.1
Immersive Weathering version: 1.20.1-2.0.0
Moonlight Lib version: fabric_1.20-2.9.8
Fabric API / QSL / Forge version: Fabric API 0.91.0+1.20.1

Other mods:
[crash report.txt](https://github.com/AstralOrdana/Immersive-Weathering/files/14221058/crash.report.txt)

**Logs:**
[latest_log.txt](https://github.com/AstralOrdana/Immersive-Weathering/files/14221099/latest_log.txt)

**To Reproduce:**
Steps to reproduce the behavior. Format it as a numbered list of steps.

1. Make a server with multiple mods on fabric 1.20.1
2. Right Click a Charred that is "active" to extinguish
3. Server Crash

Expected behavior:
Log extuingishes like in singleplayer

**Comment by AstralOrdana** [comment]
fixed for 2.0.1

**Comment by harceparcea** [comment]
Where can I get this fixed version for Forge Mod? It keeps crashing my server
