### ISSUE TITLE
(1.18.2+) Limit MossyStone blocks to set distance around Water

### ISSUE THREAD

**Issue by I2pRandom** [AstralOrdana/Immersive-Weathering#334]
**Feature:**
A config setting to Limit MossyStone blocks from 'growing' when beyond set distance from a Water source block.

**Alternatives:**
Unknown (ProjectE Ring of the goddess uses tick advancing to accelerate growth)

**Additional info:**
ProjectE ring tick advancing is forcing MossyStone growth slowly converting entire caves. 
![image](https://github.com/AstralOrdana/Immersive-Weathering/assets/42506001/a0036fbc-5e05-436a-b9f3-73bf6b8d22a8)

**Comment by AstralOrdana** [comment]
there is a limit, thats likely the top edge of an aquifer or something. 
if not, maybe its having some sort of bonemeal effect that spreads the moss
