### ISSUE TITLE
Grass variants prevent neutral/passive mob spawns

### ISSUE THREAD

**Issue by ContagiousStorm** [AstralOrdana/Immersive-Weathering#336]
While using this mod neutral and passive mobs become extremely scarce, and only show up in regions where terrain uses vanilla blocks.

Minecraft version: 1.20.1
Immersive Weathering version: 1.20.1-2.0.0
Moonlight Lib version: 1.20-2.9.10
Fabric API / QSL / Forge version: 47.2.0

Steps to reproduce the behavior. Format it as a numbered list of steps.

1. Create a new world
2. Find a region that uses terrain that is not vanilla grass
3. Wait and observe that no mobs spawn

Mobs should be able to spawn on grass.

**Comment by AstralOrdana** [comment]
fixed for 2.0.1
