### ISSUE TITLE
Earthen Clay Farmland gives Lava Bucket instead of Water Bucket

### ISSUE THREAD

**Issue by The-Spingus** [AstralOrdana/Immersive-Weathering#338]
**Description:**
When using an empty bucket to take the water out of a waterlogged Earthen Clay Farmland block, it gives you a bucket of lava instead of water.

**Versions:**
Minecraft version: 1.20.1
Immersive Weathering version: 1.20.1-2.0.0
Moonlight Lib version: 1.20-2.9.3
Fabric API / QSL / Forge version: Forge 47.2.0

**Other mods:**
N/A

**Logs:**
[latest.log](https://github.com/AstralOrdana/Immersive-Weathering/files/14317473/latest.log)
[debug.log](https://github.com/AstralOrdana/Immersive-Weathering/files/14317474/debug.log)

**To Reproduce:**
1. Waterlog an Earthen Clay Farmland block.
2. Right click the waterlogged Earthen Clay Farmland block.
3. Now you have free lava

**Expected behavior:**
When using an empty bucket, one should receive water and not lava.

**Comment by Vaskritaya** [comment]
can confirm this is also the case in 2.0.1.

**Comment by AstralOrdana** [comment]
wild stuff happens when you make a whole mod on your own

**Comment by JasdanVM** [comment]
Came here to report this.

**Comment by hypercross** [comment]
https://github.com/AstralOrdana/Immersive-Weathering/blob/8f1326d1e6acc6757be6b17499c96f5b2172465f/common/src/main/java/com/ordana/immersive_weathering/blocks/soil_types/EarthenClayFarmlandBlock.java#L123

Damn...

**Comment by AstralOrdana** [comment]
fixed for 2.0.3
