### ISSUE TITLE
Decaying cherry build-up on ground causes server crash (reproducible bug)

### ISSUE THREAD

**Issue by exocyt0sis** [AstralOrdana/Immersive-Weathering#339]
**Describe the bug:**
The Minecraft Forge server (versions below) crashes when manipulating tree leaves. It seems it has to do with piles of (cherry) leaves building up/decaying when we try to graft cherry leaves and cherry logs onto (oak) trees. During this process, piles of leaves fall to the ground. Eventually, the server crashes. The problem seems to be constant and reproducible.

**Versions:**
Minecraft version: 1.20.1
Immersive Weathering version: 1.20.1-2.0.0
Moonlight Lib version: 1.20-2.9.13
Fabric API / QSL / Forge version: Forge 47.2.0
Supplementaries 1.20-2.7.36

**Other mods:**
adchimneys 10.1.4.0
adpother 8.1.5.0
advancementframes 1.20-2.2.3
advancementplaques 1.5.1
alexscaves 1.0.9
alexsdelight 1.5
alexsmobs 1.22.7
animalistic_a 1.2.2
appleskin 2.5.1+mc1.20.1
architectury 9.1.12
ars_creo 4.0.1
ars_elemental 1.20.1-0.6.4.1
ars_nouveau 4.9.0
attributeslib 1.2.1
bakery 1.1.3
beachparty 1.1.2
betteranimationscollection 8.0.0
betterdungeons 1.20-Forge-4.0.3
bettermineshafts 1.20-Forge-4.0.4
blockui 1.20.1-1.0.139-BETA
bookshelf 20.1.7
botanypots 13.0.18
botanytrees 9.0.7
botarium 2.2.2
canary 0.3.2
candlelight 1.2.7
carryon 2.1.2.7
chefsdelight 1.0.3-forge-1.20.1
chimes 2.0.1
citadel 2.5.2
coffee_delight 1.4
colony4cc 2.6.2
comforts 6.3.5+1.20.1
commongroovylibrary 0.3.3
commonnetworking 1.0.2-1.20.1
computercraft 1.109.5
conjurer_illager 1.1.6
continents 1.1.4
corn_delight 1.0.3-1.20.1
crafttweaker 14.0.27
create 0.5.1.f
create_new_age 1.1.2
create_power_loader 1.4.0-mc1.20.1
createaddition 1.20.1-1.2.3
createdeco 2.0.1-1.20.1-forge
createdieselgenerators 1.20.1-1.2h
cullleaves 3.2.0
cupboard 1.20.1-2.1
curios 5.6.1+1.20.1
cutthrough 8.0.1
delightful 3.4.2
diagonalblocks 8.0.2
diagonalfences 8.1.3
doapi 1.2.8
domum_ornamentum 1.20-1.0.156-BETA
eatinganimation 5.0.0
electric_light 1.2
embeddium 0.3.1+mc1.20.1
embeddiumplus 1.2.3
entity_model_features 1.2.3
entity_texture_features 5.2.2
entityculling 1.6.2
epherolib 0.1.2
exposure 1.3.1
extendedslabs 3.0.1
fallingleaves 2.1.0
farmersdelight 1.20.1-1.2.4
fastbench 8.0.2
fastfurnace 8.0.1
ferritecore 6.0.1
flywheel 0.6.10-7
forge 47.2.0
forgeendertech 11.1.0.1
gateways 4.2.3
geckolib 4.4.2
gml 4.0.9
hardcore_torches 2.8
hauntedharvest 1.20-3.1.19
hostilenetworks 5.2.1
iceberg 1.1.18
illagerinvasion 8.0.4
immediatelyfast 1.2.10+1.20.4
immersive_weathering 1.20.1-2.0.0
inventorysorter 23.0.1
jei 15.3.0.1
kiwi 11.5.3
kotlinforforge 4.10.0
lucent 1.5.5
make_bubbles_pop 0.2.0-forge
mcwbridges 2.1.1
mcwdoors 1.1.0
mcwwindows 2.2.1
meadow 1.3.3
memoryleakfix 1.1.5
midnightlib 1.4.2
minecolonies 1.20.1-1.1.468-BETA
minecraft 1.20.1
mixinextras 0.2.0-beta.9
mixinsquared 0.1.1
modernfix 5.10.1+mc1.20.1
moonlight 1.20-2.9.13
mousetweaks 2.25
multipiston 1.20-1.2.32-ALPHA
mutantmonsters 8.0.6
mysterious_mountain_lib 1.4.2-1.20.1
mythicmounts 20.1-7.4.2-forge
naturalist 4.0.3
notenoughanimations 1.7.0
nyfsspiders 2.1.1
octo_economy_api 1.1.0
overweight_farming 1.20.1-2.1.0-forge
patchouli 1.20.1-84-FORGE
petshop 0.1.2
physicsmod 3.0.10
pizzacraft 7.0.7
placebo 8.6.0
puzzlesaccessapi 8.0.7
puzzleslib 8.1.16
raided 0.1.3
railways 1.5.3+forge-mc1.20.1
rats 1.20.1-8.1.2
reeses_sodium_options 1.0.4
regrowth 46.31.2
rubidium 0.7.1
saturn 0.1.2
seamless 2.2.2
sereneseasons 9.0.0.46
shipping 1.3.0
shoppy 1.0.5
shrink 1.4.5
sliceanddice 3.2.0
smartbrainlib 1.13
smarterfarmers 1.20-1.8.1
smoothboot 0.0.4
smoothchunk 1.20.1-3.5
snowrealmagic 9.1.2
spectrelib 0.13.15+1.20.1
storagedrawers 12.0.2
storageracks 1.20.1-1.7
structory 1.3.2
structure_gel 2.15.1
structurize 1.20.1-1.0.693-BETA
stylecolonies 1.3.1
supplementaries 1.20-2.7.36
tectonic 2.1
terrablender 3.0.1.4
terraform 7.0.1
terralith 2.4.11
textrues_embeddium_options 0.1.4+mc1.20.1
thirst 1.3.5
toomanyglyphs 2.3.2.12345
towntalk 1.0.1
treechop 0.18.2
villagersplus 3.1
vinery 1.4.8
workshop_for_handsome_adventurer 1.14.7
yungsapi 1.20-Forge-4.0.2
yungsextras 1.20-Forge-4.0.3

**Logs:**
[crash-2024-02-17_13.53.56-server.txt](https://github.com/AstralOrdana/Immersive-Weathering/files/14318925/crash-2024-02-17_13.53.56-server.txt)
[debug.log](https://github.com/AstralOrdana/Immersive-Weathering/files/14318926/debug.log)
[latest.log](https://github.com/AstralOrdana/Immersive-Weathering/files/14318927/latest.log)
[launcher_log.txt](https://github.com/AstralOrdana/Immersive-Weathering/files/14318928/launcher_log.txt)

(hs_err file does not exist)

**To Reproduce:**

1. Take an existing large oak tree with multiple branches.
2. One by one, replace oak leaves with cherry leaves and oak logs with cherry logs.
3. At some point, the server will crash - likely when cherry leaves decay.

**Expected behavior:**
The server shouldn't crash.

**Screenshots:**
N/A

**Additional info:**
Please see the bug report above.

**Comment by SiverDX** [comment]
![image](https://github.com/AstralOrdana/Immersive-Weathering/assets/22003703/3ae9989c-6389-4cb2-a68e-3f056a41971c)

I wonder what this new version which you are not using fixes

**Comment by AstralOrdana** [comment]
invalid report, issue already resolved in 2.0.1

**Comment by Thunderrock424242** [comment]
Is 2.0.1 out on curseforge

**Comment by szunakabeats** [comment]
i think i got the same problem ?

[crash-2024-02-25_01.27.42-server.txt](https://github.com/AstralOrdana/Immersive-Weathering/files/14394861/crash-2024-02-25_01.27.42-server.txt)
