### ISSUE TITLE
minecraft 1.20.1 forge 47.2.0 crash

### ISSUE THREAD

**Issue by Thunderrock424242** [AstralOrdana/Immersive-Weathering#343]
**Describe the bug:**
A clear and concise description of what the bug is. Include as much information as you can. Images are often helpful, especially screenshots of the F3 debug menu.
it crashed i went to thirst mod because someone told me its them now they told me its you
**Versions: (BEFORE SUBMITTING A BUG REPORT, make sure you have the most up-to-date versions of Immersive Weathering, Moonlight Lib and Supplementaries)**
Minecraft version: 1.20.1
Immersive Weathering version: 2.0.0
Moonlight Lib version: 2.10.6
Fabric API / QSL / Forge version: forge 47.2.0

**Other mods:**
List all mods that you're using; could be in the form of a list of the filenames, a crash report list, a screenshot of
the mods folder, etc. Just make sure all mods used are known!

**Logs:**
*Even if the game does not crash they may be useful!*
Please provide the following logs:
From .minecraft/logs :  "latest.log" as well as "debug.log" if it exists. From .minecraft : "launcher_log" as well as a
file that starts with "hs_err" if it exists. Note: Double check that the logs are from the correct time. ex, don't give
us a log from a month ago because you forgot to check the date.
![Screenshot 2024-02-24 130444](https://github.com/AstralOrdana/Immersive-Weathering/assets/119463825/b9e549aa-3ef6-4875-9bf0-2bd40021cd72)
[latest (10).log](https://github.com/AstralOrdana/Immersive-Weathering/files/14393993/latest.10.log)

**To Reproduce:**
Steps to reproduce the behavior. Format it as a numbered list of steps.

1.
2.
3.

**Expected behavior:**
not crash
**Screenshots:**
If applicable, add screenshots to help explain your problem. https://screenshot.help/

**Additional info:**
Add any other information that might be needed.

**Comment by SiverDX** [comment]
See https://github.com/AstralOrdana/Immersive-Weathering/issues/339

**Comment by AstralOrdana** [comment]
invalid report, youre using an outdated version

**Comment by Thunderrock424242** [comment]
> invalid report, youre using an outdated version

The new version is not on curseforge tho

**Comment by AstralOrdana** [comment]
https://modrinth.com/mod/immersive-weathering/version/f3ttCid9
