### ISSUE TITLE
Crash on chunk generation. Fabric 1.20.1

### ISSUE THREAD

**Issue by szunakabeats** [AstralOrdana/Immersive-Weathering#344]
**Describe the bug:**

my world generated and my game crashed.

**Versions:**

Minecraft version: 1.20.1
Immersive Weathering version: 1.20.1-2.0.0-fabric
Moonlight Lib version: 1.20-2.10.6-fabric
Fabric API / QSL / Forge version: fabric-api-0.92.0+1.20.1

**Other mods:**

[crash-2024-02-25_01.27.42-server.txt](https://github.com/AstralOrdana/Immersive-Weathering/files/14394867/crash-2024-02-25_01.27.42-server.txt)

**Logs:**

[latest.log](https://github.com/AstralOrdana/Immersive-Weathering/files/14394870/latest.log)

[launcher_log.txt](https://github.com/AstralOrdana/Immersive-Weathering/files/14394871/launcher_log.txt)

**To Reproduce:**

unknown sorry...

**Expected behavior:**

no crash. terrain should generate normally.

**Screenshots:**

**Additional info:**

**Comment by AstralOrdana** [comment]
invalid report, youre using an outdated version

**Comment by szunakabeats** [comment]
there is no newer version available.

![image](https://github.com/AstralOrdana/Immersive-Weathering/assets/88375166/dc6f66fa-47e5-420a-bddd-e3c9a9a919cb)

**Comment by AstralOrdana** [comment]
https://modrinth.com/mod/immersive-weathering/version/1.20.1-2.0.1
