### ISSUE TITLE
leaf piles don't play well with shaders

### ISSUE THREAD

**Issue by Heamaci** [AstralOrdana/Immersive-Weathering#35]
I'm not sure if its z axis fighting or something, but there are some visible black lines on leaf piles when light hits them. 
![2022-03-26_21 58 37](https://user-images.githubusercontent.com/67716228/160267408-b6123892-5fce-4abd-86df-40781d3d46f8.png)
![2022-03-26_22 02 00](https://user-images.githubusercontent.com/67716228/160267433-d2eae1f3-07d0-42fb-abeb-f837ac419fce.png)

**Comment by Epresin** [comment]
![image](https://user-images.githubusercontent.com/67505848/160272280-46a59c19-8eda-4676-88b4-d5c7c13ba81c.png)
selection box ？

**Comment by Heamaci** [comment]
> 
![2022-03-27_10 51 18](https://user-images.githubusercontent.com/67716228/160294069-e3da203f-516a-4afd-aefd-ec65579343fd.png)
You can see it much better here

**Comment by AstralOrdana** [comment]
That's an issue with the shaders, there's nothing we can do to change that.
