### ISSUE TITLE
Snowy blocks melting inconsistently during seasons change.

### ISSUE THREAD

**Issue by snotknobbel** [AstralOrdana/Immersive-Weathering#353]
**Describe the bug:**
When using immersive weathering together with fabric seasons, snowy blocks like stone bricks melt inconsistently in summer, for example, in plains the snow will melt of the blocks and change them back to normal stone. But in a forest biome the snowy blocks will not melt back. I've tested this in desert biomes where the snow will always melt as expected, in plains the snow will not melt in winter, and will in summer. But in forests and other biomes the snow will stay during all seasons.

**Versions: (BEFORE SUBMITTING A BUG REPORT, make sure you have the most up-to-date versions of Immersive Weathering, Moonlight Lib and Supplementaries)**
Minecraft version: 1.20.1
Immersive Weathering version: 1.20.1-2.0.1
Moonlight Lib version: fabric_1.20-2.11.0
Fabric API / QSL / Forge version: 0.92.0+1.20.1
Fabric Seasons version: 2.3+1.20

**Other mods:**
Only the mods listed above.

**Logs:**
[latest.log](https://github.com/AstralOrdana/Immersive-Weathering/files/14541968/latest.log)

**To Reproduce:**
Steps to reproduce the behavior. Format it as a numbered list of steps.

1. Place snowy blocks during winter
2. Change season to summer
3. Watch snowy blocks not melt in biomes where they should (like forests or stony shores or in plains on higher elevations)

**Expected behavior:**
Snowy blocks that form in biomes where it only snows in winter should melt in summer, this feature works in some biomes like plains but not in others.

**Screenshots:**
If applicable, add screenshots to help explain your problem. https://screenshot.help/
![2024-03-08_19 35 41](https://github.com/AstralOrdana/Immersive-Weathering/assets/44928212/a144472b-d05f-49ad-9236-4408486f13fe)
![2024-03-08_19 35 59](https://github.com/AstralOrdana/Immersive-Weathering/assets/44928212/7e5263c6-9a8a-4e7c-b73e-0ce68fdc541c)
![2024-03-08_19 36 18](https://github.com/AstralOrdana/Immersive-Weathering/assets/44928212/2a9af5c6-3b80-4703-8456-01ba7bdb3ad4)

**Additional info:**
Add any other information that might be needed.

**Comment by AstralOrdana** [comment]
was fixed in 2.0.2
