### ISSUE TITLE
compat with twigs

### ISSUE THREAD

**Issue by Heamaci** [AstralOrdana/Immersive-Weathering#36]
https://www.curseforge.com/minecraft/mc-mods/twigs

Twigs adds azalea flowers of its own and some compat would be nice, although i don't know what would be the best way to go about doing it. Maybe IW's azaleas get disabled when twigs is detected?

**Comment by AstralOrdana** [comment]
We will explore the possibility of Twigs compatibility in the future but there are a lot of overlapping features.
