### ISSUE TITLE
Stairs are missing #minecraft:stairs tag

### ISSUE THREAD

**Issue by Katranune** [AstralOrdana/Immersive-Weathering#363]
**Describe the bug:**
The stairs and slabs do not have the #minecraft:stairs tag and #minecraft:slabs tag respectively

**Versions: (BEFORE SUBMITTING A BUG REPORT, make sure you have the most up-to-date versions of Immersive Weathering, Moonlight Lib and Supplementaries)**
Minecraft version: 1.20.1
Immersive Weathering version: 2.0.1
Moonlight Lib version: 2.11.9
Fabric API / QSL / Forge version: 47.2.0

**Other mods:**
![image](https://github.com/AstralOrdana/Immersive-Weathering/assets/142047833/b810b30a-6b0e-46a3-8926-9b4aad93d1c4)
![image](https://github.com/AstralOrdana/Immersive-Weathering/assets/142047833/e41242d9-2ca4-435c-8e3d-bc118441dd37)
![image](https://github.com/AstralOrdana/Immersive-Weathering/assets/142047833/3c94370b-e940-4c1e-b8e7-fa6763082895)
![image](https://github.com/AstralOrdana/Immersive-Weathering/assets/142047833/65e438fd-e563-4698-aaf8-15b3adf75c1a)
![image](https://github.com/AstralOrdana/Immersive-Weathering/assets/142047833/406f84f3-83f1-4109-956c-ba938aa1f15a)
![image](https://github.com/AstralOrdana/Immersive-Weathering/assets/142047833/e4640969-103b-498e-b8f2-d541f9db7037)
![image](https://github.com/AstralOrdana/Immersive-Weathering/assets/142047833/3606faf7-57e6-4197-be69-56313d88f530)
![image](https://github.com/AstralOrdana/Immersive-Weathering/assets/142047833/e2866c75-2df1-4c1c-915c-40897152c8c4)
sorry for so many screenshots i have a lot of mods and the .zip was too big

**Logs:**
too big to upload and also 99% sure its unnecessary

**To Reproduce:**
Steps to reproduce the behavior. Format it as a numbered list of steps.

1. use stair
2. it does not have #minecraft:stairs tag

**Expected behavior:**
stairs from the mod to contain the #miencraft:stairs tag

**Screenshots:**
![image](https://github.com/AstralOrdana/Immersive-Weathering/assets/142047833/c7f768c8-93cd-4337-94bc-386880333540)
![image](https://github.com/AstralOrdana/Immersive-Weathering/assets/142047833/afb16977-0662-4b2b-84e7-95f648412273)
(used on a sandy stone stair)

**Additional info:**
Add any other information that might be needed.

**Comment by AstralOrdana** [comment]
fixed for 2.0.3
