### ISSUE TITLE
Cracked mud is unremovable from world generation in config files.

### ISSUE THREAD

**Issue by matzar24** [AstralOrdana/Immersive-Weathering#370]
Cracked mud is unremovable from world generation in config files.

**Comment by AstralOrdana** [comment]
worldgen isnt determined through the config, use a datapack

**Comment by matzar24** [comment]
What datapack? Cracked mud is from this mod.

**Comment by matzar24** [comment]
> worldgen isnt determined through the config, use a datapack

Simpler solution is just open it in winrar and set "size" in dry_lakebed.json to 0.
Still spawns, but in singular block and very rarely. And block is still "obtainable".
Use datapack for what? Just change value and that's it. Just wasted time for dealing with this mod...

Still wondering why Creator of this mod is trying to bring this mod down by adding stupid and invasive features...
It could have double the downloads, but just the way this mod is. It just not good to have this mod in modpack...

**Comment by AstralOrdana** [comment]
dude if you dont like it just dont use the mod
