### ISSUE TITLE
Right clicking with snow layers on leaf or sand piles consumes it and fills them

### ISSUE THREAD

**Issue by ThePegNok** [AstralOrdana/Immersive-Weathering#378]
Interacting with leaf and sand piles using snow layers increases the height of the piles

Minecraft version: 1.20.1
Immersive Weathering version: 2.0.1
Moonlight Lib version: 2.11.33
Fabric API / QSL / Forge version: Forge 47.3.0

Other mods:
![image](https://github.com/AstralOrdana/Immersive-Weathering/assets/169552316/62d0b86d-5c85-430e-b598-64be04d8ce9d)
![image](https://github.com/AstralOrdana/Immersive-Weathering/assets/169552316/a1cabe94-1030-41d4-9466-c0c563e53bc5)
![image](https://github.com/AstralOrdana/Immersive-Weathering/assets/169552316/721f371b-257d-4af7-9975-fb2265891073)

**Logs:**
[latest.log](https://github.com/user-attachments/files/15805860/latest.log)

To Reproduce:

1. Interact with any leaf pile using snow layer 
2. It consumes the layer, and raises the leaf pile height
3. Interact with any sand pile using snow layer 
4. It'll fill only the second layer of a sand pile
5. Interact with a snow layer using any pile 
6. The pile will replace the snow layer

Expected behavior:
These should not interact.

**Comment by AstralOrdana** [comment]
i could not replicate this in 2.0.2, all piles are behaving as expected. when any pile is only one layer thick, they can be replaced
![image](https://github.com/user-attachments/assets/a250e0d1-c53b-4297-8a31-66025f764c6c)
