### ISSUE TITLE
it seems that the tuff generator doesn't work well

### ISSUE THREAD

**Issue by E2-oss** [AstralOrdana/Immersive-Weathering#379]
**Describe the bug:**
To be honest, I do not find soot or soot block. So, I say that the tuff generator doesn't work well.
Or if the tuff has another way to product?
**Versions: (BEFORE SUBMITTING A BUG REPORT, make sure you have the most up-to-date versions of Immersive Weathering, Moonlight Lib and Supplementaries)**
Minecraft version: 1.20.1
Immersive Weathering version: 2.0.1
Moonlight Lib version: 2.11.33
Fabric API / QSL / Forge version: forge 47.2.21

**Other mods:**
[modslist.zip](https://github.com/user-attachments/files/15820400/modslist.zip)

**Logs:**
Sorry, I don't have "launcher_log" 
[logs.zip](https://github.com/user-attachments/files/15820460/logs.zip)

**To Reproduce:**
Steps to reproduce the behavior. Format it as a numbered list of steps.

1.create a new world
2./gamemode creative or /give ~ immersive_weathering:soot
3.you will find that there isn't the soot_block or the soot which is important for the tuff generator

**Expected behavior:**
Please add "soot_block" or "soot" to make it or tell players whether it has another way to make it, if available.

**Comment by Mendax-tech** [comment]
So is there a way to generate tuff in the end?
