### ISSUE TITLE
Incompatibility with "My Nether's Delight"

### ISSUE THREAD

**Issue by tawan256** [AstralOrdana/Immersive-Weathering#380]
Lava & Lightning turn Resurgent Soil & Resurgent Farmland into Vitrified Sand but it shouldn't. Also, both block need to be placed near/touch lava to work just like how farmland need water.

**Versions: (BEFORE SUBMITTING A BUG REPORT, make sure you have the most up-to-date versions of Immersive Weathering, Moonlight Lib and Supplementaries)**
Minecraft version: 1.20.1
Immersive Weathering version: 2.0.1
Moonlight Lib version: 2.11.41
Fabric API / QSL / Forge version: Forge 47.2.30
My Nether's Delight version: 1.6.3

**To Reproduce:**
Steps to reproduce the behavior. Format it as a numbered list of steps.

1.Place any of those 2 blocks
2.Place lava/summon lightning

**Expected behavior:**

-Lava & Lightning won't affect said blocks

**Comment by AstralOrdana** [comment]
lightning only affects blocks in the sand block tag, those blocks should be removed from that and then this issue wont occur
