### ISSUE TITLE
forge version incompat with spectrum through sinytra

### ISSUE THREAD

**Issue by annahla** [AstralOrdana/Immersive-Weathering#381]
loading a world with midnight solution placed, with spectrum through sinytra and immersive weathering for forge installed, crashes immediately.

I Don't use github so I'm not dealing with a pull request, but it's a really easy fix: have FluidInteractionRegistryMixin guard state.getBlock() based on if it's actually an instance of LiquidBlock, as spectrum can have solid block interactions.

effectively just surround the mixin in a if(state.getBlock() instanceof LiquidBlock) or whatever new fangled bullshit java added recently to make safe casts easier

**Comment by AstralOrdana** [comment]
fixed for 2.0.3
