### ISSUE TITLE
Stone Brick Recipe seems absurd

### ISSUE THREAD

**Issue by RainbowSaber** [AstralOrdana/Immersive-Weathering#385]
Currently, there is a recipe to create Stone Bricks using the Stone Cutter that converts 1 Stone/Cobblestone into 16 Stone Brick items. These can be converted to the Stone Bricks block as a 2x2 Craft. This allows the crafting of 4 Stone Bricks for each Cobblestone/Stone. This ratio is 4x what Vanilla uses and strikes me as a wierd case of volume duplication (if anything, working stones into beautiful bricks should reduce the volume, not quadruple it). I would suggest a reduction of the stone brick recipe to 4 Bricks per block as well as a removal of the cobblestone -> stone brick recipe, since it circumvents the stone smelting, which has been a staple of minecraft for decades at this point.

**Comment by AstralOrdana** [comment]
working as intended
