### ISSUE TITLE
Lack of compatibility with some mods

### ISSUE THREAD

**Issue by MistereMoth** [AstralOrdana/Immersive-Weathering#388]
As i was playing my 1.20.1 modpack i noticed that, at least on newer versions, the mod has some noticeable lack of compatibility with other mods, even some popular examples like farmer's delight that really stings.
Here are the lack of compatibility i noticed so far:
-Farmer's delight:
  *>Grass variations from the mod don't drop straw when broken by a knife
  >Two tree bark items: It's quite frustrating to have two of them with completely different uses, i'm hoping one day we can just have the treebark from this mod completely usable as FD's treebark
  >Mulch and fertile soil: Similar case to the previous one, despite those blocks being and having different functions, they still fill the same role as a better farming soil, but this is far from a frustrating case and i think both can fill different niches.
  
-Dynamic trees:
  *>Saplings from the mod can't be planted on dirt variations from the mod (ex: permafrost and silt), I don't quite remember if this is from this mod or general modded trees, but either way it's still really annoying for having to find the right grass to plant trees on.
  >Dynamic trees are dropping way too few seeds, not sure if this is really from this mod but i remember back in older versions of dynamic trees them dropping much more seeds, and i think this mod could be one of the main culprits due to messing with leaves (also they're not dropping the fallen leaves, unlike what happens with regular vanilla trees).
  
-Biomes o'Plenty:
  >Water freezes (outside serene season winter) in the shore of some biomes when it doesn't make sense to. Not sure if this is just with this mod, and i think that it may happen wtih some vanilla biomes too like some sort of rocky... beach...
  
Bonus issue:
  >Tallow is a very neat resource to make pigs useful, but it's pretty much just a worse honeycomb, and for me it's dropping from pigs even when i don't use fire aspect, and with the lack of compacting for it i'm getting way too much to know what to do with, i really think it should at least be usable as fuel or compostable since it's organic (also quark used to add a similar item that was usable as fuel, and to make candles)

**Comment by AstralOrdana** [comment]
half of these arent even iw, but i appreciate you being rude in my issues page

**Comment by AstralOrdana** [comment]
- Grass variations from the mod don't drop straw when broken by a knife
not on me to add, the only grass variant i add is Dune Grass which already does its own thing, if you want it to drop something from another mod, datapack it yourself

- Two tree bark items
good thing i added a config specifically to allow you to replace iw's bark with fd bark

- Saplings from the mod can't be planted on dirt variations from the mod
not on me, the soils are in the `dirt` block tag, not much else i can do to ensure compat

- Dynamic trees are dropping way too few seeds
no idea how this could possibly be my fault

- Water freezes (outside serene season winter)
you're mixing three expansive mods, some weird stuff is bound to show up but unless proven its my fault, what do you want me to do about it?

- but it's pretty much just a worse honeycomb
its meant to be an alternative way to farm "honeycomb" for people who dont want to make a bee farm, not meant to be better or worse. ill consider making it a fuel source

**Comment by MistereMoth** [comment]
sorry...

also thanks for letting me known about that config
about the grass variants, i specified the snowy grass, which would be grass covered by snow, which didn't drop straw last time i tested.
I will further investigate the other issues and also inform the dynamic trees team. Thanks for reading and answering.

**Comment by MistereMoth** [comment]
> * Grass variations from the mod don't drop straw when broken by a knife
>       not on me to add, the only grass variant i add is Dune Grass which already does its own thing, if you want it to drop something from another mod, datapack it yourself
> 
>     * Two tree bark items
>       good thing i added a config specifically to allow you to replace iw's bark with fd bark
> 
>     * Saplings from the mod can't be planted on dirt variations from the mod
>       not on me, the soils are in the `dirt` block tag, not much else i can do to ensure compat
> 
>     * Dynamic trees are dropping way too few seeds
>       no idea how this could possibly be my fault
> 
>     * Water freezes (outside serene season winter)
>       you're mixing three expansive mods, some weird stuff is bound to show up but unless proven its my fault, what do you want me to do about it?
> 
>     * but it's pretty much just a worse honeycomb
>       its meant to be an alternative way to farm "honeycomb" for people who dont want to make a bee farm, not meant to be better or worse. ill consider making it a fuel source

so i tried looking for that config, and all i could find was "generic bark" is that it? what do i have to type on it?

also i remembered a suggestion i wanted to include at first, which was to make snow melt in non snow biomes outside the winter season (from any mod that adds seasons) since the snow just remains and stacks until we removes them manually, plus it can make animals escape over fences, also even in snow biomes the snow should melt a little during summer so it doesn't get too crazy.

Also I forgot that water freezing into ice is a vanilla thing, so can't really blame this mod for that, my bad.

**Comment by Spektabilis** [comment]
How can i use the bark option in config, i try with true or false but nothing happen
