### ISSUE TITLE
[Feature request] Add seasoning mod support

### ISSUE THREAD

**Issue by LeFFaQ** [AstralOrdana/Immersive-Weathering#390]
**Feature:**

Adding support for mods for changing seasons such as [Serene Seasons](https://github.com/Glitchfiend/SereneSeasons). It would increase immersion.

**Additional info:**
I saw an [issue](https://github.com/AstralOrdana/Immersive-Weathering/issues/386) about ice formation. I thought it might be better to put support for Serene Seasons in a separate thread.

**Comment by AstralOrdana** [comment]
fixed for 2.0.2
