### ISSUE TITLE
Snowy stone blocks aren't going back to normal stone under conditions where snow should melt.

### ISSUE THREAD

**Issue by labradoe** [AstralOrdana/Immersive-Weathering#391]
**Describe the bug:**
Snowy stone blocks aren't going back to normal stone under conditions where snow should melt.

**Versions:**
Minecraft version: 1.20.1
Immersive Weathering version: 2.0.1
Moonlight Lib version: 2.12.17
Fabric API / QSL / Forge version: 0.16.0

**Other mods:**
Fabric Seasons

**To Reproduce:**

1. Start winter season
2. Let snow build up
3. Start spring season
4. Watch all snow melt except snowy stone blocks

**Expected behavior:**
Snowy stone blocks should be reverting back to their normal form if snow cannot form and vanilla snow melts.

**Additional info:**
This issue was fixed on the 1.19.2 version with commit 30e29f2. Later, commit 61630c0 changed the way it's determined whether to melt the snow blocks is a static value defined at >= 0.95f which is the regarded as a hot biome. I'm not sure the reasoning behind that change. The previous way this was determined (with warmEnoughToRain) was sufficient to work with normal vanilla Minecraft biomes and be compatible with a seasonal mod that changes the temp of biomes slightly during seasons. If snow forms at <= 0.15, logically it should melt at > 0.15 which is how warmEnoughToRain is defined and how vanilla snow works. I've made the change, tested it in my environment, and will make a pull request. It follows the same logic as commit 30e29f2 does.

**Comment by AstralOrdana** [comment]
fixed for 2.0.2
