### ISSUE TITLE
Need more config options for generators

### ISSUE THREAD

**Issue by ModDehBird** [AstralOrdana/Immersive-Weathering#394]
Im making a modpack but immersive weathering seems to have hard coded in generators that cause magma to spawn under lightning strikes and tuff to have alternative recipe that completely nullifies the more complex one. if stuff like this could be toggleable itd be appreciated

Using version 1.20.1-2.0.2

**Comment by AstralOrdana** [comment]
they arent hardcoded, those are all data-driven

**Comment by ModDehBird** [comment]
Wait then how do i change it then?
Or can i not change it at all?

Also sorry im asking these here, i dont have any phone data and cant just ask in the discord :[
