### ISSUE TITLE
Replenishing Foliage

### ISSUE THREAD

**Issue by ImpulsiveLass** [AstralOrdana/Immersive-Weathering#405]
**Feature:**

In essence, grass, flowers, etc that are the normal small flora for a biome will occasionally appear on the respective ground block.
I.E. a grass block in a plains may spawn grass above it, or a flower. In the nether you may see a warped mushroom spawn on the ground.

This feature would really just exist to replenish the foliage of a biome if it either spawned pretty flat and empty or x, y, or z stripped it away.

**Alternatives:**

Don't really know the best way to code it tbh.

**Additional info:**

May be an idea to put limitations on it or some way to give it variation so you don't get the same flower to spawn on every block, rather a random flora every 2-3 blocks or something.

**Comment by MehVahdJukaar** [comment]
Well that's basically *the* main feature of the mod 💀

**Comment by ImpulsiveLass** [comment]
@MehVahdJukaar Are you sure? Tell me more.

I’ve never observed this, even with a high tick speed.

**Comment by ImpulsiveLass** [comment]
Oh shit, I just found it in the wiki, been foaming at the mouth over no mod with/for that. How long it’s been there?

(if you couldn’t tell yes I am a ESS Major and ocd pilled)

**Comment by MehVahdJukaar** [comment]
basically was pretty much the first feature added to the mod, *the* literal core of the mod itself
