### ISSUE TITLE
1.16.5 please , I really need to combine mods And only 1.16.5 has the cool mods

### ISSUE THREAD

**Issue by offbem** [AstralOrdana/Immersive-Weathering#410]
**Feature:**

Describe what the new feature should be.  Generally, the more information you provide, the faster we can decide on whether it is something we can/will do.

**Alternatives:**

If this feature has possible alternatives, such as different implementation methods, list them here.

**Additional info:**

Any other info should go here.  With more complicated features, it is geneally worth mentioning even the smallest of details you wish to see if the suggestion is approved and implemented.

**Comment by AstralOrdana** [comment]
inappropriate use of issues form

**Comment by offbem** [comment]
@AstralOrdana Sorry! , but the tab doesn't have comments 😓
