### ISSUE TITLE
[Suggestion] Add Leaf Pile Support for other mods that add custom leaves

### ISSUE THREAD

**Issue by Peach774** [AstralOrdana/Immersive-Weathering#43]
Right now, leaf piles only spawn below vanilla trees which can leave modded biomes feeling empty. I dont know how difficult it would be to check what mods have leaf blocks and work back from there (potentially automatically?) but there are several commonly used mods that add leaves such as biomes o plenty, biomes you'll go, quark, premium wood, etc.
It would be nice if there were leaf piles for these mods

**Comment by MehVahdJukaar** [comment]
Added on forge

**Comment by AstralOrdana** [comment]
not possible for fabric
