### ISSUE TITLE
[1.18.2] Icicles form inside player created structures

### ISSUE THREAD

**Issue by Peach774** [AstralOrdana/Immersive-Weathering#44]
Icicles are forming inside my house because its snowing even though the roof is made of wood - this shouldnt happen.
![image](https://user-images.githubusercontent.com/5171184/161703996-f6e6dcdf-19db-4d68-bb17-602e85b96263.png)

**Comment by AstralOrdana** [comment]
please specify which number version you are playing on and whether its fabric or forge.

**Comment by Peach774** [comment]
> please specify which number version you are playing on and whether its fabric or forge.

1.0.6 Forge. I did manage to fix the issue by making my roof 1.5 blocks thick instead of 0.5 blocks thick, but they still shouldnt be forming inside my contained structure.....

**Comment by MehVahdJukaar** [comment]
Definitely a bug since icicles should only form when it's snowing in a block next to them. Can you confirm that that formed when the roof was fully built?

**Comment by Peach774** [comment]
my roof was half slabs on the bottom half - once it was full blocks, it stopped.

**Comment by MehVahdJukaar** [comment]
Shouldn't be an issue on forge anymore

**Comment by AstralOrdana** [comment]
done for 2.5.0 fabric
