### ISSUE TITLE
[1.18.2-1.1.1 Forge] Parity Issues

### ISSUE THREAD

**Issue by Bobisnotap** [AstralOrdana/Immersive-Weathering#45]
The recent forge version has some... weird things going on.
- Vitrified Sand is not properly being created, instead of the sand vitrifying, the lava does??
- Humus is missing from Dark Forests.
- Grass Blocks cannot be sheared out of their fertile state (though the fertile true/false blockstates exist)

**Comment by MehVahdJukaar** [comment]
What can I say except I forgot 💀

**Comment by MehVahdJukaar** [comment]
added everything there except humus patches (they can still generate naturally underneath leaf piles)
