### ISSUE TITLE
Unable to breed Bees, is this a bug or a feature?

### ISSUE THREAD

**Issue by SharkieTV** [AstralOrdana/Immersive-Weathering#47]
Tested alone: immersive_weathering-2.4.0.jar
FABRIC: 0.13.3 fabric-api-0.50.0+1.18.2.jar
Version: 1.18.2

Unable to breed Bees, is this a bug or a feature?

**Comment by AstralOrdana** [comment]
This is a bug that also extends to rabbits being unable to breed, we are working on a fix for the next version.

**Comment by AstralOrdana** [comment]
fixed for next version
![image](https://user-images.githubusercontent.com/62686557/163730378-090e7653-a4ab-4ef1-a58f-c12eb7d753d1.png)
