### ISSUE TITLE
Ars Nouveau Archwood leaf piles are missing textures

### ISSUE THREAD

**Issue by paulhlschr** [AstralOrdana/Immersive-Weathering#51]
![image](https://user-images.githubusercontent.com/20583201/164893727-469e674f-4cc2-48c8-93fe-6464c2a6a746.png)

### Specifications
- Minecraft 1.18.2
- Immersive Weathering version: 1.18.2-1.2.0
- Forge 40.1.0

**Comment by MehVahdJukaar** [comment]
shouldnt happen anymore
