### ISSUE TITLE
[SUGGESTION]Add the compat with the Sandpaper in Create Mod

### ISSUE THREAD

**Issue by hrsthrt74** [AstralOrdana/Immersive-Weathering#55]
The Sandpaper item in Create Mod can be used to remove the rust of copper blocks, however, it can't remove the rust of the blocks in this mod.
Maybe adding this feature can improve the gameplay, so I hope to add the feature.

(Sorry for my poor English)
(Sorry if I should post this issue in Create's Issues)

**Comment by MehVahdJukaar** [comment]
is that a crafting recipe or does that work when you click on them with it? I'm assuming create just checks if a block is an oxidisable block which cut iron isnt since it rusts instead. oh also if you need some alternative to axe scraping know that supplementaries soap does work on them

**Comment by hrsthrt74** [comment]
Sorry for my unclear description. I mean when I click on the Waxed Rusted Cut Iron Block with the Sandpaper, it doesn't work.
The Sandpaper can be used to remove both the wax and the rust of the vanilla and Create's copper blocks by click on them. However, I can't do it on the blocks in Immersive Weathering.
I don't know the technical details of this mod, but please add this feature as long as it's easy to do.
This mod is awesome, and thank you for making this great mod.

(btw I can't use the soap in Supplementaries to remove the rust of the blocks in Immersive Weathering.)
(Minecraft version: `1.18.2`, Mod version: `supplementaries-1.18.2-1.3.7`,`immersive_weathering-1.18.2-1.2.7`,`create-mc1.18.2_v0.4.1`)

**Comment by JieningYu** [comment]
import snownee's lychee tweaker and just add recipes(?

**Comment by hrsthrt74** [comment]
@JieningYu Thanks. I will have a try.
