### ISSUE TITLE
Integration with BlueMaps

### ISSUE THREAD

**Issue by ilarramendi** [AstralOrdana/Immersive-Weathering#58]
Helo!
If this is not relevant for this place please delete.
First of all thanks for the amazing mod, im trying to make it work with BlueMap and most stuff looks great but the texture for the fallen leaves exclusively from leaves that other mods add are not available, this happens because bluemap scans for textures inside mods .jar and in Immersive-Weathering the only textures that are included are for the vanilla trees (fallen leaves look perfect).
Im guessing Immresive-Weathering somehow generates models for all leaves in all mods?
Would it be posible to access or export these models?

**Comment by MehVahdJukaar** [comment]
I'll add a config like I have on my other mods. It will simply save those textures to disk into a debug folder in your installation dir
