### ISSUE TITLE
Crash related to Werewolves mod (werewolves:stone_altar_fire_bowl)

### ISSUE THREAD

**Issue by MaxWasUnavailable** [AstralOrdana/Immersive-Weathering#59]
[crash-2022-05-15_14.37.29-server.txt](https://github.com/AstralOrdana/Immersive-Weathering/files/8711573/crash-2022-05-15_14.37.29-server.txt)

**Comment by AstralOrdana** [comment]
fixed for future version

**Comment by AstralOrdana** [comment]
could you confirm that this has been fixed on 2.5.3?

**Comment by MaxWasUnavailable** [comment]
No issues so far. Though I believe my players might have moved their altars below roofs? I'll be sure to let you know if it happens again though!
