### ISSUE TITLE
Axe on iron bars no effect

### ISSUE THREAD

**Issue by johalun** [AstralOrdana/Immersive-Weathering#62]
Hey

According to the docs you can scrape off rust using an axe however this does not work on iron bars. It does work on iron plate blocks though.

Version 2.4.0 in Valhelsia Enhanced Vanilla 1.2.1 modpack.

**Comment by AstralOrdana** [comment]
I dont remember fixing this bug but it is no longer present in the development version of the mod so it will be fixed when the next update is released
