### ISSUE TITLE
Crash on fabric server when right-clicking

### ISSUE THREAD

**Issue by YeahBoi321** [AstralOrdana/Immersive-Weathering#63]
crash report file
[crash-2022-05-24_16.22.46-client.txt](https://github.com/AstralOrdana/Immersive-Weathering/files/8766000/crash-2022-05-24_16.22.46-client.txt)

**Comment by YeahBoi321** [comment]
did not mean to do anything

**Comment by AstralOrdana** [comment]
what did you click on?

**Comment by YeahBoi321** [comment]
it does this with anything, whether it be any bricks with a pickaxe, logs with an axe, mossy stuff with shears, etc.

**Comment by AstralOrdana** [comment]
can you recreate this issue and give a list of any other mods you were using?
