### ISSUE TITLE
[2.5.3] Improvement: Only make players take damage in cold water

### ISSUE THREAD

**Issue by Chribit** [AstralOrdana/Immersive-Weathering#71]
I had to disable the cold water freezing because all my modded animals were dying in the water... I don't think penguins should die in cold water for instance :)

I think it would be cool if this feature only affected players OR one could blacklist mobs in the config file for that kind of damage

**Comment by MehVahdJukaar** [comment]
That's a nice suggestion, we'll definitely add it

**Comment by Chribit** [comment]
Good point! I‘ll have to do that for multiple mobs then… mammoths from adventurez died on permafrost as well :D

**Comment by AstralOrdana** [comment]
done for upcoming update. Add modded mobs to the vanilla tag: `entity_types/freeze_immune_entity_types` to make them immune.
