### ISSUE TITLE
[2.5.3] Improvement: Ability to disable thorn damage from pine leaf piles etc.

### ISSUE THREAD

**Issue by Chribit** [AstralOrdana/Immersive-Weathering#72]
Started to play with this mod on a private server with some friends. Turns out building a base in a spruce forest can get pretty annoying at times, if you haven‘t got any leggings yet.

I‘d propose the ability to disable thorns damage from weeds and pine leaf piles separately in the config.

**Comment by AstralOrdana** [comment]
this is intentional gameplay, put on some pants.

**Comment by Chribit** [comment]
depending on the other mods one has installed, pants may not be the top priority for a couple of minecraft days though... and even then may not be super easy to come by for multiple players
