### ISSUE TITLE
The campfire_from_soot recipe is mildly borked

### ISSUE THREAD

**Issue by foul-fortune-feline** [AstralOrdana/Immersive-Weathering#75]
Instead of accepting soot in the place of coal/charcoal, it accepts air/nothing, meaning you can forgo the use of either and make a campfire entirely out of sticks and logs

The issue is that you need to switch `"tag"` to `"item"` in the key for `"C"`, or alternatively create a tag `"immersive_weathering:soot"` and put the item in

**Comment by AstralOrdana** [comment]
fixed by removing the recipe
