### ISSUE TITLE
[Fabric 1.18.2] Leaf Piles are placed on slabs and other not full blocks

### ISSUE THREAD

**Issue by 0gp** [AstralOrdana/Immersive-Weathering#89]
![image](https://user-images.githubusercontent.com/62187599/173504975-24db5167-08f2-4d63-96f3-5aba04b6aa39.png)

**Comment by AstralOrdana** [comment]
fixed for upcoming 1.19 version

**Comment by MSandro** [comment]
no plans to further support 1.18.2? :(

**Comment by 0gp** [comment]
thank you so much for fixing it for 1.18.2 👍
