### ISSUE TITLE
Add LambdaBetterGrass metadata to grass-like blocks

### ISSUE THREAD

**Issue by magneticflux-** [AstralOrdana/Immersive-Weathering#94]
Info for adding metadata: https://github.com/LambdAurora/LambdaBetterGrass/blob/1.19/documentation/METADATA_GRASS_FORMAT.md

Blocks that could use grass-like connections:
- Humus
- Fluvisol
- Vertisol
- Cryosol
- Rooted Grass Block

**Comment by AstralOrdana** [comment]
I am open to someone making a pull-request for this but I dont have the time to implement the compat myself.

**Comment by AkashiiKun** [comment]
Working on it. Expect a pull request tomorrow.
![image](https://user-images.githubusercontent.com/44606942/174498100-55e29ffb-c75a-477a-9512-79026b797327.png)

**Comment by magneticflux-** [comment]
@AkashiiKun Was this ever implemented?
